### ISSUE TITLE
Honeycomb button menu doesn't work, auto-closes on touch on mobile

### ISSUE THREAD

**Issue by ocangelo** [Nerwyn/android-tv-card#107]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
3.8.1

**Browser and Operating System:**
HomeAssistant App on Android 14, Pixel 6

**Description of problem:**
Using honeycomb menu on a remote button: https://github.com/Sian-Lee-SA/honeycomb-menu
When touching a button the honeycomb options display as a menu for a split second and then the menu auto closes.
If i hold the touch on the button then the menu stays up without problems.

This only happens on the android app, when triggering from my pc on chrome it works completely fine on a normal click, so it's probably something touch related.

issue is not present when using the other tv-card, everything there works perfectly: https://github.com/usernein/tv-card

**Your Full Remote Config**

```
type: custom:android-tv-card
      remote_id: remote.roku_ultra
      media_player_id: media_player.receiver
      rows:
        - - power_on
          - power_off
        - - plex
          - youtube
          - spotify
        - - main
          - projector
        - - slider
        - - navigation_buttons
        - - return
          - home
          - source
        - - rewind
          - play
          - fast_forward
      row_styles:
        rows:
          padding: 12px
      custom_sources:
        plex:
          icon: mdi:plex
          service: media_player.select_source
          service_data:
            entity_id: media_player.roku_ultra
            source: Plex - Free Movies & TV
        youtube:
          icon: mdi:youtube
          service: media_player.select_source
          service_data:
            entity_id: media_player.roku_ultra
            source: YouTube
        spotify:
          icon: mdi:spotify
          service: media_player.select_source
          service_data:
            entity_id: media_player.roku_ultra
            source: Spotify Music
        main:
          icon: mdi:television
          service: media_player.onkyo_select_hdmi_output
          service_data:
            entity_id: media_player.receiver
            hdmi_output: out
        projector:
          icon: mdi:projector
          service: media_player.onkyo_select_hdmi_output
          service_data:
            entity_id: media_player.receiver
            hdmi_output: out-sub
        source:
          icon: mdi:hdmi-port
          service: honeycomb
          service_data:
            entity: media_player.receiver
            buttons:
              - icon: mdi:television
                tap_action:
                  action: call-service
                  service: media_player.select_source
                  service_data:
                    entity_id: media_player.receiver
                    source: strm-box
              - icon: mdi:minidisc
                tap_action:
                  action: call-service
                  service: media_player.select_source
                  service_data:
                    entity_id: media_player.receiver
                    source: cd
              - icon: mdi:sony-playstation
                tap_action:
                  action: call-service
                  service: media_player.select_source
                  service_data:
                    entity_id: media_player.receiver
                    source: bd
              - icon: mdi:nintendo-switch
                tap_action:
                  action: call-service
                  service: media_player.select_source
                  service_data:
                    entity_id: entity
                    source: game
      custom_keys:
        power_on:
          icon: mdi:power
          service: script.remote_power_on
        power_off:
          icon: mdi:power-sleep
          service: script.remote_power_off
        enter:
          icon: mdi:circle
          service: remote.send_command
          service_data:
            entity_id: remote.roku_ultra
            command: select
        return:
          icon: mdi:arrow-left
          service: remote.send_command
          service_data:
            entity_id: remote.roku_ultra
            command: back
        play:
          icon: mdi:play-pause
          service: media_player.media_play_pause
          service_data:
            entity_id: media_player.roku_ultra
        rewind:
          icon: mdi:rewind
          service: remote.send_command
          service_data:
            entity_id: remote.roku_ultra
            command: reverse
        fast_forward:
          icon: mdi:fast-forward
          service: remote.send_command
          service_data:
            entity_id: remote.roku_ultra
            command: forward
```

**Additional information:**
