### ISSUE TITLE
Img buttons broke

### ISSUE THREAD

**Issue by jeroen-vd-nl** [Nerwyn/android-tv-card#111]
Yeah yeah all latest etc etc, I even rebooted HA

after the last update my card is ruined. Especially the images don’t work anymore, thus I’m missing a complete line of buttons.

 I also have no clue where that blue comes from all of a sudden.

![IMG_1642](https://github.com/user-attachments/assets/2acfd3f2-19e9-420f-8d38-9d30ffa0c4df)
![IMG_1641](https://github.com/user-attachments/assets/498c024a-ea6e-49d2-a53d-3c10657f02dd)

```yaml
  canalplus:
    style:
      background-image: >-
        url("https://images.crunchbase.com/image/upload/c_pad,h_170,w_170,f_auto,b_white,q_auto:eco,dpr_1/v1425199547/gkrrhijmxcsw0376zude.jpg")
      background-size: 50px
      background-repeat: no-repeat
      background-position: center
    tap_action:
      action: call-service
      service: media_player.select_source
      data:
        source: CANAL+
  Spotify:
    style:
      background-image: >-
        url("https://upload.wikimedia.org/wikipedia/commons/1/19/Spotify_logo_without_text.svg")
      background-size: 48px
      background-repeat: no-repeat
      background-position: center
    tap_action:
      action: call-service
      service: media_player.select_source
      data:
        source: Spotify
  YouTube:
    style:
      background-image: >-
        url("https://upload.wikimedia.org/wikipedia/commons/0/09/YouTube_full-color_icon_%282017%29.svg")
      background-size: 48px
      background-repeat: no-repeat
      background-position: center
    tap_action:
      action: call-service
      service: media_player.select_source
      data:
        source: YouTube
  F1:
    style:
      background-image: url("https://upload.wikimedia.org/wikipedia/commons/3/33/F1.svg")
      background-size: 48px
      background-repeat: no-repeat
      background-position: center
    tap_action:
      action: call-service
      service: media_player.select_source
      data:
        source: F1 TV
  nos:
    style:
      background-image: url("https://upload.wikimedia.org/wikipedia/commons/b/b9/NOS_logo.svg")
      background-size: 48px
      background-repeat: no-repeat
      background-position: center
    tap_action:
      action: call-service
      service: media_player.select_source
      data:
        source: NOS
```

**Comment by Nerwyn** [comment]
I just pushed a fix for older webview devices which should also fix the blue color, but I'll look into the image buttons once I push the fix to my other project.

**Comment by Nerwyn** [comment]
Add this to your custom button styles:

```yaml
height: 50px
width: 50px
border-radius: 0px
```

Can you add the rest of your card config, so I can figure out what's wrong with the direction buttons?

**Comment by jeroen-vd-nl** [comment]
Thanks for your very fast reply.

your suggestion works! 👍 Got my buttons back.
Also my wife is very happy with that.

I didn’t receive the update yet through HACS, so I can’t see if the blue color is fixed, I will keep you updated about this.

the location of the crossbar I assume it has something to do with the mushroom theme I use. When I initially created it, I had to pixelf*ck already. I think I just have to do that again. So I think that’s not in scope for this issue.

**Comment by Nerwyn** [comment]
Crossbar? Do you mean the direction buttons?  Some of the v4 changes like changing how buttons are made snuck into this release, so it is still possible a bug.

**Comment by jeroen-vd-nl** [comment]
```
type:%20custom%3Aandroid-tv-card%0Aremote_id%3A%20remote.woonkamer%0Amedia_player_id%3A%20media_player.woonkamer%0Aslider_id%3A%20media_player.55oled903_12%0Aautofill_entity_id%3A%20true%0Arows%3A%0A%20%20-%20-%20-%20-%20dpad%0A%20%20%20%20-%20-%20-%20play%0A%20%20%20%20%20%20%20%20-%20pause%0A%20%20%20%20%20%20%20%20-%20power%0A%20%20%20%20%20%20-%20-%20menu%0A%20%20%20%20%20%20%20%20-%20home%0A%20%20%20%20%20%20%20%20-%20hue%0A%20%20%20%20%20%20-%20-%20volume_down%0A%20%20%20%20%20%20%20%20-%20volume_up%0A%20%20%20%20%20%20%20%20-%20volume_mute%0A%20%20-%20-%20-%20-%20canalplus%0A%20%20%20%20%20%20%20%20-%20Spotify%0A%20%20%20%20%20%20%20%20-%20YouTube%0A%20%20%20%20%20%20%20%20-%20F1%0A%20%20%20%20%20%20%20%20-%20nos%0A%20%20-%20-%20-%20-%20touchpad%0Atouchpad_style%3A%0A%20%20background-image%3A%20%3E-%0A%20%20%20%20url(%22https%3A//upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Apple_logo_grey.svg/505px-Apple_logo_grey.svg.png%22)%0A%20%20background-size:%20200px%0A%20%20background-repeat:%20no-repeat%0A%20%20background-position:%20center%0Acustom_actions:%0A%20%20power:%0A%20%20%20%20icon:%20mdi:power%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20key%0A%20%20%20%20%20%20key:%20wakeup%0A%20%20%20%20hold_action:%0A%20%20%20%20%20%20action:%20key%0A%20%20%20%20%20%20key:%20suspend%0A%20%20menu:%0A%20%20%20%20icon:%20mdi:arrow-left-bold%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20key%0A%20%20%20%20%20%20key:%20menu%0A%20%20home:%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20key%0A%20%20%20%20%20%20key:%20home%0A%20%20%20%20hold_action:%0A%20%20%20%20%20%20action:%20more-info%0A%20%20up:%0A%20%20%20%20style:%0A%20%20%20%20%20%20z-index:%202%0A%20%20%20%20%20%20'--size':%2050px%0A%20%20%20%20%20%20left:%20'-6px'%0A%20%20%20%20%20%20top:%20'-1px'%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20key%0A%20%20%20%20%20%20key:%20up%0A%20%20down:%0A%20%20%20%20style:%0A%20%20%20%20%20%20z-index:%202%0A%20%20%20%20%20%20'--size':%2050px%0A%20%20%20%20%20%20left:%20'-6px'%0A%20%20%20%20%20%20bottom:%205px%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20key%0A%20%20%20%20%20%20key:%20down%0A%20%20left:%0A%20%20%20%20style:%0A%20%20%20%20%20%20z-index:%202%0A%20%20%20%20%20%20'--size':%2050px%0A%20%20%20%20%20%20left:%202px%0A%20%20%20%20%20%20top:%20'-2px'%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20key%0A%20%20%20%20%20%20key:%20left%0A%20%20right:%0A%20%20%20%20style:%0A%20%20%20%20%20%20z-index:%202%0A%20%20%20%20%20%20'--size':%2050px%0A%20%20%20%20%20%20top:%20'-2px'%0A%20%20%20%20%20%20right:%2018px%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20key%0A%20%20%20%20%20%20key:%20right%0A%20%20volume_up:%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20call-service%0A%20%20%20%20%20%20service:%20scene.turn_on%0A%20%20%20%20%20%20target:%0A%20%20%20%20%20%20%20%20entity_id:%20scene.surround_volume_up%0A%20%20volume_down:%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20call-service%0A%20%20%20%20%20%20service:%20scene.turn_on%0A%20%20%20%20%20%20target:%0A%20%20%20%20%20%20%20%20entity_id:%20scene.surround_volume_down%0A%20%20volume_mute:%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20call-service%0A%20%20%20%20%20%20service:%20scene.turn_on%0A%20%20%20%20%20%20target:%0A%20%20%20%20%20%20%20%20entity_id:%20scene.surround_power_toggle%0A%20%20play:%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20key%0A%20%20%20%20%20%20key:%20play%0A%20%20pause:%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20key%0A%20%20%20%20%20%20key:%20pause%0A%20%20center:%0A%20%20%20%20style:%0A%20%20%20%20%20%20color:%20rgba(150,%20150,%20150,%200.5)%0A%20%20%20%20%20%20background:%20rgba(100,%20100,%20100,%200.3)%0A%20%20%20%20%20%20border-radius:%2010em%0A%20%20%20%20%20%20'--size':%2066px%0A%20%20%20%20%20%20width:%2032px%0A%20%20%20%20%20%20height:%2032px%0A%20%20%20%20%20%20top:%20'-12px'%0A%20%20%20%20%20%20left:%202px%0A%20%20%20%20%20%20margin:%20'-64px'%0A%20%20%20%20%20%20padding:%2064px%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20key%0A%20%20%20%20%20%20key:%20select%0A%20%20%20%20double_tap_action:%0A%20%20%20%20%20%20action:%20key%0A%20%20%20%20%20%20key:%20menu%0A%20%20hue:%0A%20%20%20%20icon:%20mdi:television-ambient-light%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20call-service%0A%20%20%20%20%20%20service:%20switch.toggle%0A%20%20%20%20%20%20target:%0A%20%20%20%20%20%20%20%20entity_id:%20switch.tvwk_ambilight_hue%0A%20%20%20%20style:%0A%20%20%20%20%20%20color:%20%7C%0A%20%20%20%20%20%20%20%20%7B%25%20if%20is_state(%22switch.tvwk_ambilight_hue%22,%20%22on%22)%20%25%7D%0A%20%20%20%20%20%20%20%20rgba(254,211,140,255)%0A%20%20%20%20%20%20%20%20%7B%25%20endif%20%25%7D%0A%20%20canalplus:%0A%20%20%20%20style:%0A%20%20%20%20%20%20background-image:%20%3E-%0A%20%20%20%20%20%20%20%20url(%22https://images.crunchbase.com/image/upload/c_pad,h_170,w_170,f_auto,b_white,q_auto:eco,dpr_1/v1425199547/gkrrhijmxcsw0376zude.jpg%22)%0A%20%20%20%20%20%20background-size:%2050px%0A%20%20%20%20%20%20background-repeat:%20no-repeat%0A%20%20%20%20%20%20background-position:%20center%0A%20%20%20%20%20%20height:%2050px%0A%20%20%20%20%20%20width:%2050px%0A%20%20%20%20%20%20border-radius:%200px%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20call-service%0A%20%20%20%20%20%20service:%20media_player.select_source%0A%20%20%20%20%20%20data:%0A%20%20%20%20%20%20%20%20source:%20CANAL+%0A%20%20Spotify:%0A%20%20%20%20style:%0A%20%20%20%20%20%20background-image:%20%3E-%0A%20%20%20%20%20%20%20%20url(%22https://upload.wikimedia.org/wikipedia/commons/1/19/Spotify_logo_without_text.svg%22)%0A%20%20%20%20%20%20background-size:%2048px%0A%20%20%20%20%20%20background-repeat:%20no-repeat%0A%20%20%20%20%20%20background-position:%20center%0A%20%20%20%20%20%20height:%2050px%0A%20%20%20%20%20%20width:%2050px%0A%20%20%20%20%20%20border-radius:%200px%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20call-service%0A%20%20%20%20%20%20service:%20media_player.select_source%0A%20%20%20%20%20%20data:%0A%20%20%20%20%20%20%20%20source:%20Spotify%0A%20%20YouTube:%0A%20%20%20%20style:%0A%20%20%20%20%20%20background-image:%20%3E-%0A%20%20%20%20%20%20%20%20url(%22https://upload.wikimedia.org/wikipedia/commons/0/09/YouTube_full-color_icon_%25282017%2529.svg%22)%0A%20%20%20%20%20%20background-size:%2048px%0A%20%20%20%20%20%20background-repeat:%20no-repeat%0A%20%20%20%20%20%20background-position:%20center%0A%20%20%20%20%20%20height:%2050px%0A%20%20%20%20%20%20width:%2050px%0A%20%20%20%20%20%20border-radius:%200px%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20call-service%0A%20%20%20%20%20%20service:%20media_player.select_source%0A%20%20%20%20%20%20data:%0A%20%20%20%20%20%20%20%20source:%20YouTube%0A%20%20F1:%0A%20%20%20%20style:%0A%20%20%20%20%20%20background-image:%20url(%22https://upload.wikimedia.org/wikipedia/commons/3/33/F1.svg%22)%0A%20%20%20%20%20%20background-size:%2048px%0A%20%20%20%20%20%20background-repeat:%20no-repeat%0A%20%20%20%20%20%20background-position:%20center%0A%20%20%20%20%20%20height:%2050px%0A%20%20%20%20%20%20width:%2050px%0A%20%20%20%20%20%20border-radius:%200px%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20call-service%0A%20%20%20%20%20%20service:%20media_player.select_source%0A%20%20%20%20%20%20data:%0A%20%20%20%20%20%20%20%20source:%20F1%20TV%0A%20%20nos:%0A%20%20%20%20style:%0A%20%20%20%20%20%20background-image:%20url(%22https://upload.wikimedia.org/wikipedia/commons/b/b9/NOS_logo.svg%22)%0A%20%20%20%20%20%20background-size:%2048px%0A%20%20%20%20%20%20background-repeat:%20no-repeat%0A%20%20%20%20%20%20background-position:%20center%0A%20%20%20%20%20%20height:%2050px%0A%20%20%20%20%20%20width:%2050px%0A%20%20%20%20%20%20border-radius:%200px%0A%20%20%20%20tap_action:%0A%20%20%20%20%20%20action:%20call-service%0A%20%20%20%20%20%20service:%20media_player.select_source%0A%20%20%20%20%20%20data:%0A%20%20%20%20%20%20%20%20source:%20NOS%0A
```

**Comment by jeroen-vd-nl** [comment]
ok, in that case:

```yaml
type: custom:android-tv-card
remote_id: remote.woonkamer
media_player_id: media_player.woonkamer
slider_id: media_player.55oled903_12
autofill_entity_id: true
rows:
  - - - - dpad
    - - - play
        - pause
        - power
      - - menu
        - home
        - hue
      - - volume_down
        - volume_up
        - volume_mute
  - - - - canalplus
        - Spotify
        - YouTube
        - F1
        - nos
  - - - - touchpad
touchpad_style:
  background-image: >-
    url("https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Apple_logo_grey.svg/505px-Apple_logo_grey.svg.png")
  background-size: 200px
  background-repeat: no-repeat
  background-position: center
custom_actions:
  power:
    icon: mdi:power
    tap_action:
      action: key
      key: wakeup
    hold_action:
      action: key
      key: suspend
  menu:
    icon: mdi:arrow-left-bold
    tap_action:
      action: key
      key: menu
  home:
    tap_action:
      action: key
      key: home
    hold_action:
      action: more-info
  up:
    style:
      z-index: 2
      '--size': 50px
      left: '-6px'
      top: '-1px'
    tap_action:
      action: key
      key: up
  down:
    style:
      z-index: 2
      '--size': 50px
      left: '-6px'
      bottom: 5px
    tap_action:
      action: key
      key: down
  left:
    style:
      z-index: 2
      '--size': 50px
      left: 2px
      top: '-2px'
    tap_action:
      action: key
      key: left
  right:
    style:
      z-index: 2
      '--size': 50px
      top: '-2px'
      right: 18px
    tap_action:
      action: key
      key: right
  volume_up:
    tap_action:
      action: call-service
      service: scene.turn_on
      target:
        entity_id: scene.surround_volume_up
  volume_down:
    tap_action:
      action: call-service
      service: scene.turn_on
      target:
        entity_id: scene.surround_volume_down
  volume_mute:
    tap_action:
      action: call-service
      service: scene.turn_on
      target:
        entity_id: scene.surround_power_toggle
  play:
    tap_action:
      action: key
      key: play
  pause:
    tap_action:
      action: key
      key: pause
  center:
    style:
      color: rgba(150, 150, 150, 0.5)
      background: rgba(100, 100, 100, 0.3)
      border-radius: 10em
      '--size': 66px
      width: 32px
      height: 32px
      top: '-12px'
      left: 2px
      margin: '-64px'
      padding: 64px
    tap_action:
      action: key
      key: select
    double_tap_action:
      action: key
      key: menu
  hue:
    icon: mdi:television-ambient-light
    tap_action:
      action: call-service
      service: switch.toggle
      target:
        entity_id: switch.tvwk_ambilight_hue
    style:
      color: |
        {% if is_state("switch.tvwk_ambilight_hue", "on") %}
        rgba(254,211,140,255)
        {% endif %}
  canalplus:
    style:
      background-image: >-
        url("https://images.crunchbase.com/image/upload/c_pad,h_170,w_170,f_auto,b_white,q_auto:eco,dpr_1/v1425199547/gkrrhijmxcsw0376zude.jpg")
      background-size: 50px
      background-repeat: no-repeat
      background-position: center
      height: 50px
      width: 50px
      border-radius: 0px
    tap_action:
      action: call-service
      service: media_player.select_source
      data:
        source: CANAL+
  Spotify:
    style:
      background-image: >-
        url("https://upload.wikimedia.org/wikipedia/commons/1/19/Spotify_logo_without_text.svg")
      background-size: 48px
      background-repeat: no-repeat
      background-position: center
      height: 50px
      width: 50px
      border-radius: 0px
    tap_action:
      action: call-service
      service: media_player.select_source
      data:
        source: Spotify
  YouTube:
    style:
      background-image: >-
        url("https://upload.wikimedia.org/wikipedia/commons/0/09/YouTube_full-color_icon_%282017%29.svg")
      background-size: 48px
      background-repeat: no-repeat
      background-position: center
      height: 50px
      width: 50px
      border-radius: 0px
    tap_action:
      action: call-service
      service: media_player.select_source
      data:
        source: YouTube
  F1:
    style:
      background-image: url("https://upload.wikimedia.org/wikipedia/commons/3/33/F1.svg")
      background-size: 48px
      background-repeat: no-repeat
      background-position: center
      height: 50px
      width: 50px
      border-radius: 0px
    tap_action:
      action: call-service
      service: media_player.select_source
      data:
        source: F1 TV
  nos:
    style:
      background-image: url("https://upload.wikimedia.org/wikipedia/commons/b/b9/NOS_logo.svg")
      background-size: 48px
      background-repeat: no-repeat
      background-position: center
      height: 50px
      width: 50px
      border-radius: 0px
    tap_action:
      action: call-service
      service: media_player.select_source
      data:
        source: NOS
```

Update concerning the blue color: it's there in the mobile, but not on the laptop

**Comment by Nerwyn** [comment]
Ah I see what you mean, that's a lot of CSS adjustments to not only the direction keys but the center key as well. I think this should get you back to your old styles:

```yaml
  center:
    style:
      --icon-color: rgba(150, 150, 150, 0.5)
      background: rgba(100, 100, 100, 0.3)
      border-radius: 10em
      '--size': 66px
      width: 32px
      height: 32px
      margin: '-80px'
      padding: 80px
    tap_action:
      action: key
      key: select
    double_tap_action:
      action: key
      key: menu
  up:
    style:
      z-index: 2
      '--size': 50px
    tap_action:
      action: key
      key: up
  down:
    style:
      z-index: 2
      '--size': 50px
      bottom: 2px
    tap_action:
      action: key
      key: down
  left:
    style:
      z-index: 2
      '--size': 50px
      left: 10px
    tap_action:
      action: key
      key: left
  right:
    style:
      z-index: 2
      '--size': 50px
      right: 10px
    tap_action:
      action: key
      key: right
```
As for the blue color, I noticed it happened on iPhones but not any other platform but I think I've fixed it. Can you try the latest 3.8.2 alpha?
