### ISSUE TITLE
Button color styling ineffective after upgrade

### ISSUE THREAD

**Issue by jsamr** [Nerwyn/android-tv-card#113]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

I did clear cache a couple of times, until the new "jellyfin" icon works out of the box.

**Release with the issue:** 3.9.1

**Last working release (if known):** 3.8.2

**Browser and Operating System:**

Reproducible both in

- Android Companion App - 2024.7.3-full
- Arc browser - 1.53.0 (52080)

**Description of problem:**

Button color styling does not work anymore.

**Your Full Remote Config**

Here is my minimal reproduction

```yaml
type: custom:android-tv-card
remote_id: remote.XXX
media_player_id: media_player.XXX
custom_actions:
  jellyfin:
    style:
      color: '#7C71CC'
  youtube:
    style:
      color: '#FC0B1C'
  primevideo:
    style:
      color: '#48B0E3'
  spotify:
    style:
      color: '#1CD760'
rows:
  - - jellyfin
    - youtube
    - primevideo
    - spotify
```

![image](https://github.com/user-attachments/assets/f6be72d6-a11c-4c69-8a9a-61195ef59395)

**Comment by jsamr** [comment]
A little inspection shows the color is properly applied to the `<button>` element, but fails to propagate to the `<svg>` element down below, which has below styling:

```css
    fill: var(--icon-primary-color, currentcolor);
```

![image](https://github.com/user-attachments/assets/60180c88-29a8-4b4e-8a4e-2f3c55837862)

Hence the current workaround is to set the CSS variable in place of the `color` attribute:

```
type: custom:android-tv-card
remote_id: remote.tcl_tv_cocon
media_player_id: media_player.tcl_tv_cocon_android
custom_actions:
  jellyfin:
    style:
      --icon-primary-color: '#7C71CC'
  youtube:
    style:
      --icon-primary-color: '#FC0B1C'
  primevideo:
    style:
      --icon-primary-color: '#48B0E3'
  spotify:
    style:
      --icon-primary-color: '#1CD760'
rows:
  - - jellyfin
    - youtube
    - primevideo
    - spotify
```

![image](https://github.com/user-attachments/assets/620b98ca-8349-45ee-87fb-da4b3b3f8ced)
