### ISSUE TITLE
--icon-color broken on mobile?

### ISSUE THREAD

**Issue by ocangelo** [Nerwyn/android-tv-card#116]
**Checklist:**

- [v ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**
3.9.4

**Last working release (if known):**
3.8.9?

**Browser and Operating System:**
Android companion app

**Description of problem:**
the replacement of color with --icon-color works fine on the webui/chrome but on android no colors are applied.
(the same page that has colors working on the webui doesn't work on the companion app)

webui screenshot
![remote_webui](https://github.com/user-attachments/assets/191d44d7-9736-4936-b153-0442c78d634d)

android screenshot
![remote_android](https://github.com/user-attachments/assets/82bc631f-3003-453f-b443-a3e902cd184b)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Remote Config**

```

type: custom:tabbed-card
options: {}
styles:
  '--mdc-tab-text-label-color-default': rgb(100, 100, 100)
  '--mdc-tab-color-default': rgb(120, 120, 120)
tabs:
  - attributes:
      label: Remote
    card:
      type: custom:android-tv-card
      autofill_entity_id: true
      remote_id: remote.roku_ultra
      media_player_id: media_player.receiver
      keyboard_id: remote.roku_ultra
      keyboard_mode: ROKU
      button_style:
        '--icon-color': |-
          {% if is_state("media_player.receiver", "off") %} 
            rgb(50, 50, 50)
          {% endif %}
      rows:
        - - power_toggle
          - light_toggle
        - - plex
          - youtube
          - spotify
        - - main
          - projector
        - - navigation_buttons
        - - volume_down
          - volume_mute
          - volume_up
        - - return
          - home
          - source
          - keyboard
        - - rewind
          - play_pause
          - fast_forward
          - menu
      row_styles:
        rows:
          margin: 12px
        row-4:
          margin-top: 0px
        row-6:
          margin-bottom: 0px
      custom_actions:
        light_toggle:
          icon: mdi:chandelier
          style:
            '--icon-color': |-
              {% if is_state("light.living_room_lights", "off") %} 
                green
              {% else %} 
                red
              {% endif %}
          tap_action:
            service: light.toggle
            data:
              entity_id: light.living_room_lights
        select_app:
          style:
            '--icon-color': |-
              {% if is_state("media_player.receiver", "off") %} 
                rgb(50, 50, 50)
              {% endif %}
          service: media_player.select_source
          service_data:
            entity_id: media_player.roku_ultra
        plex:
          style:
            '--icon-color': orange
          template: select_app
          service_data:
            source: Plex - Free Movies & TV
        youtube:
          style:
            '--icon-color': red
          template: select_app
          service_data:
            source: YouTube
        spotify:
          style:
            '--icon-color': green
          template: select_app
          service_data:
            source: Spotify Music
        main:
          icon: mdi:television
          service: media_player.onkyo_select_hdmi_output
          service_data:
            entity_id: media_player.receiver
            hdmi_output: out
        projector:
          icon: mdi:projector
          service: media_player.onkyo_select_hdmi_output
          service_data:
            entity_id: media_player.receiver
            hdmi_output: out-sub
        source:
          icon: mdi:hdmi-port
          tap_action:
            action: call-service
            service: honeycomb
            target:
              entity_id: media_player.receiver
            data:
              buttons:
                - icon: mdi:television
                  tap_action:
                    action: call-service
                    service: media_player.select_source
                    service_data:
                      entity_id: media_player.receiver
                      source: strm-box
                - icon: mdi:record-player
                  tap_action:
                    action: call-service
                    service: media_player.select_source
                    service_data:
                      entity_id: media_player.receiver
                      source: cd
                - icon: mdi:sony-playstation
                  tap_action:
                    action: call-service
                    service: media_player.select_source
                    service_data:
                      entity_id: media_player.receiver
                      source: bd
                - icon: mdi:nintendo-switch
                  tap_action:
                    action: call-service
                    service: media_player.select_source
                    service_data:
                      entity_id: entity
                      source: game
      custom_keys:
        remote_command:
          service: remote.send_command
          service_data:
            entity_id: remote.roku_ultra
        power_toggle:
          icon: mdi:power
          service: |-
            {% if is_state("media_player.receiver", "off") %} 
              script.remote_power_on
            {% else %} 
              script.remote_power_off
            {% endif %} 
          style:
            '--icon-color': |-
              {% if is_state("media_player.receiver", "off") %} 
                green
              {% else %} 
                red
              {% endif %} 
        up:
          icon: mdi:arrow-up-bold
          template: remote_command
          service_data:
            command: up
        down:
          icon: mdi:arrow-down-bold
          template: remote_command
          service_data:
            command: down
        left:
          icon: mdi:arrow-left-bold
          template: remote_command
          service_data:
            command: left
        right:
          icon: mdi:arrow-right-bold
          template: remote_command
          service_data:
            command: right
        center:
          icon: mdi:circle
          template: remote_command
          service_data:
            command: select
        return:
          icon: mdi:arrow-left
          template: remote_command
          service_data:
            command: back
        home:
          icon: mdi:home
          template: remote_command
          service_data:
            command: home
        play_pause:
          service: media_player.media_play_pause
          service_data:
            entity_id: media_player.roku_ultra
        rewind:
          icon: mdi:rewind
          template: remote_command
          service_data:
            command: reverse
        fast_forward:
          icon: mdi:fast-forward
          template: remote_command
          service_data:
            command: forward
        volume_mute:
          icon: mdi:volume-off
          template: remote_command
          service_data:
            command: volume_mute
  - attributes:
      icon: mdi:speaker
    card:
      type: custom:android-tv-card
      autofill_entity_id: true
      remote_id: remote.receiver
      media_player_id: media_player.receiver
      rows:
        - - navigation_buttons
        - - stereo
          - direct
          - audio-mode-cycle
      custom_keys:
        set_listening_mode:
          service: script.onkyo_command
          data:
            onkyo_cmd: listening-mode
        stereo:
          icon: mdi:music
          template: set_listening_mode
          data:
            onkyo_cmd_value: all-ch-stereo
        direct:
          icon: mdi:surround-sound-5-1
          template: set_listening_mode
          data:
            onkyo_cmd_value: direct
        audio-mode-cycle:
          icon: mdi:volume-vibrate
          template: set_listening_mode
          data:
            onkyo_cmd_value: up
  - attributes:
      icon: mdi:television-box
    card:
      type: custom:android-tv-card
      autofill_entity_id: true
      remote_id: remote.tv_samsung
      media_player_id: media_player.tv_samsung
      rows:
        - - navigation_buttons
        - - return
          - settings
          - power_on
          - power_off
      custom_keys:
        up:
          icon: mdi:arrow-up-bold
          service: remote.send_command
          service_data:
            command: KEY_UP
        down:
          icon: mdi:arrow-down-bold
          service: remote.send_command
          service_data:
            command: KEY_DOWN
        left:
          icon: mdi:arrow-left-bold
          service: remote.send_command
          service_data:
            command: KEY_LEFT
        right:
          icon: mdi:arrow-right-bold
          service: remote.send_command
          service_data:
            command: KEY_RIGHT
        center:
          icon: mdi:circle
          service: remote.send_command
          service_data:
            command: KEY_ENTER
        return:
          icon: mdi:arrow-left
          service: remote.send_command
          service_data:
            command: KEY_RETURN
        settings:
          icon: mdi:wrench
          service: remote.send_command
          service_data:
            command: KEY_MENU
        power_on:
          icon: mdi:power
          service: media_player.turn_on
          style:
            '--icon-color': |-
              {% if is_state("media_player.tv_samsung", "off") %} 
                green
              {% else %} 
                black
              {% endif %}         
        power_off:
          icon: mdi:power
          service: media_player.turn_off
          style:
            '--icon-color': |-
              {% if is_state("media_player.tv_samsung", "on") %} 
                red
              {% else %} 
                black
              {% endif %}         
  - attributes:
      icon: mdi:projector
    card:
      type: custom:android-tv-card
      autofill_entity_id: true
      remote_id: remote.samsung_7_series_58
      media_player_id: media_player.samsung_7_series_58
      rows:
        - - navigation_buttons

```

**Additional information:**
