### ISSUE TITLE
Menu button not working (NVIDIA SHIELD)

### ISSUE THREAD

**Issue by NezarecSh** [Nerwyn/android-tv-card#117]
**Checklist:**

- [●] I updated to the latest version available
- [●] I cleared the cache of my browser

**Release with the issue:**
Version 3.9.4

**Last working release (if known):**
Not sure, but it used to work a couple of months ago.

**Browser and Operating System:**
Home assistant companion app
OS version: 13.0
Core: 2024.8.1

**Description of problem:**
The menu button for nvidia shield TV isn't working anymore. I can tap it and it has haptics but it doesnt do anything to the TV.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Remote Config**

```yaml
- type: custom:android-tv-card
    card_mod:
      style: |
        ha-card {
        --ha-card-background: #000000;
        }
    remote_id: remote.nvidia_shield
    slider_id: media_player.nvidia_shield
    slider_style:
      --background: '#0E0E11'
    touchpad_style:
      background: '#0E0E11'
    enable_touchpad_feedback: false
    enable_slider_feedback: false
    keyboard_id: media_player.android_tv_<my_ip_address>
    rows:
      - - keyboard
        - slider
      - - touchpad
      - - stremio
      - - back
        - home
        - menu
      - - rewind
        - previous
        - play_pause
        - next
        - fast_forward
    custom_sources:
      stremio:
        icon: mdi:play-box-outline
        source: stremio://

```

**Additional information:**
I have the card inside of a bubble-pop-up card. Not sure if that matters at all, since it used to work just fine before.

**Comment by Nerwyn** [comment]
If all the other buttons are working it sounds like an issue with your device. What happens if you use the [actions dev tool](http://homeassistant.local:8123/developer-tools/action) to call the following action?

```yaml
action: remote.send_command
target:
  entity_id: remote.nvidia_shield
data:
  command: MENU
```

**Comment by NezarecSh** [comment]
> If all the other keys are working it sounds like an issue with your device. What happens if you use the [actions dev tool](http://homeassistant.local:8123/developer-tools/action) to call the following action?
> 
> ```yaml
> action: remote.send_command
> target:
>   entity_id: remote.nvidia_shield
> data:
>   command: MENU
> ```

It doesn't do anything /:
Does that mean it's an issue with my device? The official nvidia shield app remote works just fine though.

**Comment by Nerwyn** [comment]
Yeah it seems so. You could also try sending a `CENTER` hold action as it's usually treated the same as the menu key on Android TV.

**Comment by Gtasian** [comment]
This works with the shield. 

```
action: androidtv.adb_command
target:
  entity_id: media_player.shield
data:
  command: am start -a android.settings.SETTINGS
```
