### ISSUE TITLE
Icon color no longer seems to work

### ISSUE THREAD

**Issue by priyankub** [Nerwyn/android-tv-card#122]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**
I use CSS style and color to change color of icons based on current selected source, and status of lights etc. It seems to have stopped working after some update:

```
    icon: mdi:desktop-tower
    tap_action:
      action: call-service
      service: media_player.select_source
      service_data:
        entity_id: media_player.home_theater_2
        source: PC
    style:
      color: |
        {% if is_state_attr("media_player.home_theater_2","source","PC") %}
        #007243
        {% endif %}  
```

```
  light:
    icon: mdi:lightbulb-cfl-spiral
    style:
      color: |
        {% if states("switch.av_room_light_switch") == "on" %}
          #cfbf0c
        {% endif %}
    tap_action:
      action: call-service
      service: homeassistant.toggle
      target:
        entity_id: switch.av_room_light_switch
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Remote Config**

```yaml

```

**Additional information:**

**Comment by Nerwyn** [comment]
Use `--icon-color` in the style field instead. It was a minor breaking change in version 3.9.0. in the version 4 beta, you can instead use the icon CSS selector.

```css
.icon {
  {% if states("switch.av_room_light_switch") == "on" %}
  color: #cfbf0c;
  {% endif %}
}
```
