### ISSUE TITLE
Platform: Unified Remote and Mousepad

### ISSUE THREAD

**Issue by Nerwyn** [Nerwyn/android-tv-card#124]
- Add new platform Unified Remote using [this custom integration](https://github.com/DaviPtrs/hass-unified-remote).
- Add a new mousepad element for use with this integration.

**Comment by Nerwyn** [comment]
Keyboard support and basic default keys have been added in the 4.3.0 alpha.

For mouse support, I found [this bit of code](https://github.com/unifiedremote/Remotes/blob/master/Main/Basic%20Input/remote.lua#L41-L44) which can be called using the following command:

```yaml
action: unified_remote.call
data:
  target: desktop
  remote_id: Relmtech.Basic Input
  action: delta
  extras:
    Values:
      - Value: 0
      - Value: 200
      - Value: 200
```
