### ISSUE TITLE
Need help with config after 4.0.0 update

### ISSUE THREAD

**Issue by Dillton** [Nerwyn/android-tv-card#128]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
4.0.0
**Last working release (if known):**
3.9.4
**Browser and Operating System:**
Chrome + Win11

**Description of problem:**
I have built a card which uses combination of android tv and kodi functions which was a bit tricky but eventually I succeeded and everything works and covers my needs.
Hovever after 4.0.0 several buttons like youtube, spotify, fast_forward, rewind etc.. are not working correctly after update when platform is Kodi and now I am stuck in fixing this.

Below is my original and converted config and also screenshot of card before and after update.
Can anyone help me with that please?

**Your Full Remote Config**
Working config in 3.9.4
```yaml
type: custom:android-tv-card
remote_id: remote.chromecast_google_tv
media_player_id: media_player.chromecast_google_tv_kodi
keyboard_id: media_player.chromecast_google_tv_kodi
platform: KODI
autofill_entity_id: true
touchpad_style:
  height: 350px
rows:
  - - search
    - power
  - - vol_buttons
  - - tv
    - youtube
    - spotify
    - kodi
  - - touchpad
  - - rewind
    - play_pause
    - stop
    - fast_forward
  - - back
    - home
    - keyboard
custom_sources:
  kodi:
    icon: mdi:kodi
    source: org.xbmc.kodi
custom_actions:
  power:
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Application.Quit
  tv:
    tap_action:
      action: perform-action
      perform_action: media_player.select_source
      target:
        entity_id: media_player.chromecast_google_tv_adb
      data:
        source: cz.sledovanitv.android
  center:
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.Select
    hold_action:
      perform_action: kodi.call_method
      data:
        method: Input.ContextMenu
    double_tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.ShowOSD
  up:
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.Up
  down:
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.Down
  left:
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.Left
  right:
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.Right
  back:
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.Back
  home:
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.Home
  textbox:
    icon: mdi:keyboard
```

Converted config in 4.0.0
```yaml
type: custom:android-tv-card
remote_id: remote.chromecast_google_tv
media_player_id: media_player.chromecast_google_tv_kodi
keyboard_id: media_player.chromecast_google_tv_kodi
platform: Kodi
autofill_entity_id: true
rows:
  - - search
    - power
  - - volume_buttons
  - - tv
    - youtube
    - spotify
    - kodi
  - - touchpad
  - - rewind
    - play_pause
    - stop
    - fast_forward
  - - back
    - home
    - keyboard
custom_actions:
  - type: button
    name: power
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Application.Quit
      action: perform-action
    icon: mdi:power
  - type: button
    name: tv
    tap_action:
      action: perform-action
      perform_action: media_player.select_source
      target:
        entity_id: media_player.chromecast_google_tv_adb
      data:
        source: cz.sledovanitv.android
    icon: mdi:television-box
  - type: button
    name: center
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.Select
      action: perform-action
    icon: mdi:checkbox-blank-circle
    hold_action:
      perform_action: kodi.call_method
      data:
        method: Input.ContextMenu
      action: perform-action
    double_tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.ShowOSD
      action: perform-action
  - type: button
    name: up
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.Up
      action: perform-action
    hold_action:
      action: repeat
    icon: mdi:chevron-up
  - type: button
    name: down
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.Down
      action: perform-action
    hold_action:
      action: repeat
    icon: mdi:chevron-down
  - type: button
    name: left
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.Left
      action: perform-action
    hold_action:
      action: repeat
    icon: mdi:chevron-left
  - type: button
    name: right
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.Right
      action: perform-action
    hold_action:
      action: repeat
    icon: mdi:chevron-right
  - type: button
    name: back
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.Back
      action: perform-action
    icon: mdi:keyboard-backspace
  - type: button
    name: home
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.Home
      action: perform-action
    icon: mdi:home
  - type: button
    name: textbox
    tap_action:
      action: textbox
    icon: mdi:keyboard
  - icon: mdi:kodi
    name: kodi
    tap_action:
      source: org.xbmc.kodi
      action: source
    type: button
  - type: touchpad
    name: touchpad
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.Select
      action: perform-action
    up:
      tap_action:
        perform_action: kodi.call_method
        data:
          method: Input.Up
        action: perform-action
      hold_action:
        action: repeat
      name: up
      type: button
    down:
      tap_action:
        perform_action: kodi.call_method
        data:
          method: Input.Down
        action: perform-action
      hold_action:
        action: repeat
      name: down
      type: button
    left:
      tap_action:
        perform_action: kodi.call_method
        data:
          method: Input.Left
        action: perform-action
      hold_action:
        action: repeat
      name: left
      type: button
    right:
      tap_action:
        perform_action: kodi.call_method
        data:
          method: Input.Right
        action: perform-action
      hold_action:
        action: repeat
      name: right
      type: button
    styles: |-
      toucharea {
        height: 350px;
      }
    hold_action:
      perform_action: kodi.call_method
      data:
        method: Input.ContextMenu
      action: perform-action
    double_tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.ShowOSD
      action: perform-action
```

**Additional information:**
3.9.4
![image](https://github.com/user-attachments/assets/a6c2a705-d992-4460-b335-8a4bb74cb9d7)

4.0.0
![image](https://github.com/user-attachments/assets/71a41549-885c-4cd1-95da-b13b81f63c65)

**Comment by Nerwyn** [comment]
It looks like you're using the Android TV platform sources and media controls, but the Kodi platform keyboard. I'd say you should create custom actions for the sources and media controls and remap them to the default Android TV keys.

The easiest way to go about that is to create a separate remote, set it's platform to `Android TV`, create custom actions for the keys and sources you want to copy as if you were overwriting default ones, and copy the autofilled default key and source information from those custom actions to this remote.

Try this, I think I got everything:

```yaml
type: custom:android-tv-card
remote_id: remote.chromecast_google_tv
media_player_id: media_player.chromecast_google_tv_kodi
keyboard_id: media_player.chromecast_google_tv_kodi
platform: Kodi
autofill_entity_id: true
rows:
  - - search
    - power
  - - volume_buttons
  - - tv
    - youtube
    - spotify
    - kodi
  - - touchpad
  - - rewind
    - play_pause
    - stop
    - fast_forward
  - - back
    - home
    - keyboard
custom_actions:
  - type: button
    name: power
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Application.Quit
      action: perform-action
    icon: mdi:power
    entity_id: media_player.chromecast_google_tv_kodi
  - type: button
    name: tv
    tap_action:
      action: perform-action
      perform_action: media_player.select_source
      target:
        entity_id: media_player.chromecast_google_tv_adb
      data:
        source: cz.sledovanitv.android
    icon: mdi:television-box
  - type: button
    name: textbox
    tap_action:
      action: textbox
    icon: mdi:keyboard
    entity_id: media_player.chromecast_google_tv_kodi
  - icon: mdi:kodi
    name: kodi
    tap_action:
      source: org.xbmc.kodi
      action: source
    type: button
  - type: touchpad
    name: touchpad
    tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.Select
      action: perform-action
    up:
      tap_action:
        perform_action: kodi.call_method
        data:
          method: Input.Up
        action: perform-action
      hold_action:
        action: repeat
      name: up
      type: button
    down:
      tap_action:
        perform_action: kodi.call_method
        data:
          method: Input.Down
        action: perform-action
      hold_action:
        action: repeat
      name: down
      type: button
    left:
      tap_action:
        perform_action: kodi.call_method
        data:
          method: Input.Left
        action: perform-action
      hold_action:
        action: repeat
      name: left
      type: button
    right:
      tap_action:
        perform_action: kodi.call_method
        data:
          method: Input.Right
        action: perform-action
      hold_action:
        action: repeat
      name: right
      type: button
    styles: |-
      toucharea {
        height: 350px;
      }
    hold_action:
      perform_action: kodi.call_method
      data:
        method: Input.ContextMenu
      action: perform-action
    double_tap_action:
      perform_action: kodi.call_method
      data:
        method: Input.ShowOSD
      action: perform-action
  - type: button
    name: volume_up
    tap_action:
      action: key
      key: VOLUME_UP
    icon: mdi:volume-high
    hold_action:
      action: repeat
  - type: button
    name: volume_down
    tap_action:
      action: key
      key: VOLUME_DOWN
    icon: mdi:volume-medium
    hold_action:
      action: repeat
  - type: button
    name: volume_mute
    tap_action:
      action: key
      key: VOLUME_MUTE
    icon: mdi:volume-low
    hold_action:
      action: repeat
  - type: button
    name: youtube
    tap_action:
      action: source
      source: vnd.youtube://
    icon: mdi:youtube
  - type: button
    name: spotify
    tap_action:
      action: source
      source: spotify://
    icon: mdi:spotify
  - type: button
    name: rewind
    tap_action:
      action: key
      key: MEDIA_REWIND
    icon: mdi:rewind
  - type: button
    name: play_pause
    tap_action:
      action: key
      key: MEDIA_PLAY_PAUSE
    icon: mdi:play-pause
  - type: button
    name: stop
    tap_action:
      action: key
      key: MEDIA_STOP
    icon: mdi:stop
  - type: button
    name: fast_forward
    tap_action:
      action: key
      key: MEDIA_FAST_FORWARD
    icon: mdi:fast-forward
```
