### ISSUE TITLE
update old config not working

### ISSUE THREAD

**Issue by ciclapt** [Nerwyn/android-tv-card#129]
Hi!
Great work with the remote!
Just updated and, as expected, lost the visuals.
When i click the update old config button, it doesn't do anything.
Posting my yaml here:

```yaml
type: custom:android-tv-card
remote_id: remote.shield_android_tv
media_player_id: media_player.shield_android_tv
keyboard_id: media_player.android_tv_192_168_1_16
power_row:
  - null
  - - - - toggle_tv
  - null
apps_row:
  - - stremio
  - - smartube
  - - siptv
volumetv_row:
  - - volume_down
  - - volume_mute
  - - volume_up
navigation_row: touchpad
source_row:
  - - back
  - - home
  - - meotv
media_control_row:
  - - rewind
  - - play
  - - pause
  - - fast_forward
keyb_row:
  - - null
  - - - keyboard
  - - null
custom_sources:
  meo:
    icon: mdi:television-box
    source: ottapp://
  stremio:
    icon: mdi:movie
    source: stremio://
  smartube:
    icon: mdi:youtube
    source: https://www.youtube.com/
custom_keys:
  toggle_tv:
    icon: mdi:power
    service: switch.toggle
    service_data:
      entity_id: switch.tv_plug
  volume_up:
    icon: mdi:volume-plus
    service: script.volume_up_on_speakers
    service_data:
      entity_id: remote.samsung_tv
  volume_down:
    icon: mdi:volume-minus
    service: script.volume_down_on_speakers_duplicate
    service_data:
      entity_id: remote.samsung_tv
  volume_mute:
    icon: mdi:volume-mute
    service: script.volume_mute_on_speakers
    service_data:
      entity_id: remote.samsung_tv
  siptv:
    icon: mdi:television
    service: script.open_siptv
    service_data:
      entity_id: remote.shield_android_tv
  meotv:
    icon: mdi:television-box
    service: script.open_meo
    service_data:
      entity_id: remote.shield_android_tv
custom_actions: []
```

Thanks

**Comment by Nerwyn** [comment]
It's working fine for me with your remote config? Are there any errors in the browser logs? It looks like I did reference the wrong config object when deleting deprecated `_row` keys but that shouldn't affect anything.

```yaml
type: custom:android-tv-card
remote_id: remote.shield_android_tv
media_player_id: media_player.shield_android_tv
keyboard_id: media_player.android_tv_192_168_1_16
custom_actions:
  - icon: mdi:power
    name: toggle_tv
    tap_action:
      action: perform-action
      perform_action: switch.toggle
      data: {}
      target:
        entity_id: switch.tv_plug
    type: button
  - type: button
    name: volume_up
    tap_action:
      action: perform-action
      perform_action: script.volume_up_on_speakers
      data: {}
      target:
        entity_id: remote.samsung_tv
    hold_action:
      action: repeat
    icon: mdi:volume-plus
  - type: button
    name: volume_down
    tap_action:
      action: perform-action
      perform_action: script.volume_down_on_speakers_duplicate
      data: {}
      target:
        entity_id: remote.samsung_tv
    hold_action:
      action: repeat
    icon: mdi:volume-minus
  - type: button
    name: volume_mute
    tap_action:
      action: perform-action
      perform_action: script.volume_mute_on_speakers
      data: {}
      target:
        entity_id: remote.samsung_tv
    icon: mdi:volume-mute
  - icon: mdi:television
    name: siptv
    tap_action:
      action: perform-action
      perform_action: script.open_siptv
      data: {}
      target:
        entity_id: remote.shield_android_tv
    type: button
  - icon: mdi:television-box
    name: meotv
    tap_action:
      action: perform-action
      perform_action: script.open_meo
      data: {}
      target:
        entity_id: remote.shield_android_tv
    type: button
  - icon: mdi:television-box
    name: meo
    tap_action:
      source: ottapp://
      action: source
    type: button
  - type: button
    name: stremio
    tap_action:
      source: stremio://
      action: source
    icon: mdi:movie
  - icon: mdi:youtube
    name: smartube
    tap_action:
      source: https://www.youtube.com/
      action: source
    type: button
rows:
  - - null
    - - - - toggle_tv
    - null
  - - - stremio
    - - smartube
    - - siptv
  - - - volume_down
    - - volume_mute
    - - volume_up
  - - touchpad
  - - - back
    - - home
    - - meotv
  - - - rewind
    - - play
    - - pause
    - - fast_forward
  - - - null
    - - - keyboard
    - - null
```
