### ISSUE TITLE
Inconsistent controls since 4.0.1

### ISSUE THREAD

**Issue by madjetey** [Nerwyn/android-tv-card#131]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:4.0.3

**Last working release (if known):3.9.4

**Browser and Operating System:**

**Description of problem:**

**Your Full Remote Config**

```
type: custom:android-tv-card
title: Clean card
rows:
  - - power
    - home
    - play_pause
    - menu
  - - touchpad
  - - back
    - volume_down
    - volume_up
    - keyboard
custom_actions: []
remote_id: remote.android_tv_192_168_1_216
keyboard_id: media_player.android_tv_192_168_1_216
media_player_id: media_player.android_tv_192_168_1_216
```

```
type: custom:mini-media-player
entity: media_player.android_tv_192_168_1_216
name: Main Hall Cast
source: icon
artwork: material
hide:
  power: true
  controls: false
  toggle_power: true
  runtime: false
  jump: false
  play-pause: false
  source: true
  mute: true
shortcuts:
  columns: 4
  hide_when_off: true
  buttons:
    - icon: mdi:youtube-tv
      type: source
      id: com.teamsmart.videomanager.tv
    - icon: mdi:vlc
      type: source
      id: VLC
    - icon: mdi:youtube
      type: source
      id: YouTube
    - icon: mdi:cast
      type: source
      id: HDMI 4
    - icon: mdi:lightbulb
      type: service
      id: light.toggle
      data:
        entity_id: light.main_hall_lights_l2
    - icon: mdi:phone-classic
      type: service
      id: browser_mod.popup
      data:
        deviceID:
          - this
        title: Tablet Setup
        timeout: 900
        dismissable: true
        size: normal
        content:
          type: vertical-stack
          cards:
            - type: custom:android-tv-card
    - icon: mdi:remote-tv
      type: service
      id: browser_mod.popup
      data:
        action: fire-dom-event
        browser_mod:
          command: popup
          data:
            title: Cast Controls
            dismissable: true
            size: normal
            card_mod:
              style: |
                ha-dialog$:
                  div.mdc-dialog div.mdc-dialog__scrim {
                    backdrop-filter: blur(5px);
                  }
                ha-dialog {
                  --vertical-align-dialog: center !important;
                  --mdc-dialog-min-width: 50px;
                  --mdc-dialog-max-width: 400px;
                  --mdc-dialog-min-height: 350px !important;
                  }
            content:
              type: vertical-stack
              cards:
                - type: custom:android-tv-card
                  card_mod:
                    style: |
                      }    ha-card {
                      margin-bottom: 20px;    }
                  remote_id: media_player.android_tv_192_168_1_216
                  keyboard_id: media_player.android_tv_192_168_1_216
                  media_player_id: media_player.android_tv_192_168_1_216
                  rows:
                    - - power
                      - home
                      - menu
                    - - navigation_touchpad
                    - - back
                      - keyboard
                  button_style:
                    '--size': 32px
                    color: grey
                    border-width: 3px;
                    box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.9);
                    border-radius: 50%;
                    backgound-color: black;
                    background-opacity: 50%;
                    padding: 8px;
                  touchpad_style:
                    background-image: url("/local/fingerprint.png")
                    background-size: 150px
                    background-repeat: no-repeat
                    background-position: center
                    opacity: 0.5
                    box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.9);
                    height: 160px
                    width: 160px
                  enable_double_click: true
                  double_click_keycode: menu
                  custom_keys:
                    power:
                      service: androidtv.adb_command
                      service_data:
                        entity_id: media_player.android_tv_192_168_1_216
                        command: POWER
                    back:
                      service: androidtv.adb_command
                      service_data:
                        entity_id: media_player.android_tv_192_168_1_216
                        command: BACK
                    home:
                      service: androidtv.adb_command
                      service_data:
                        entity_id: media_player.android_tv_192_168_1_216
                        command: HOME
                    menu:
                      service: androidtv.adb_command
                      service_data:
                        entity_id: media_player.android_tv_192_168_1_216
                        command: MENU
                    up:
                      service: androidtv.adb_command
                      service_data:
                        entity_id: media_player.android_tv_192_168_1_216
                        command: UP
                    left:
                      icon: local/16x16.png
                      service: androidtv.adb_command
                      service_data:
                        entity_id: media_player.android_tv_192_168_1_216
                        command: LEFT
                    center:
                      icon: mdi:arrow-expand-all
                      service: androidtv.adb_command
                      service_data:
                        entity_id: media_player.android_tv_192_168_1_216
                        command: ENTER
                    right:
                      service: androidtv.adb_command
                      service_data:
                        entity_id: media_player.android_tv_192_168_1_216
                        command: RIGHT
                    down:
                      service: androidtv.adb_command
                      service_data:
                        entity_id: media_player.android_tv_192_168_1_216
                        command: DOWN
group: true
max_volume: '25'
min_volume: '1'
volume_stateless: true
show_progress: true
sound_mode: full
scale: '1.1'
info: scroll
hold_action:
  action: more-info
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Cast Controls
      dismissable: true
      size: normal
      card_mod:
        style: |
          ha-dialog$:
            div.mdc-dialog div.mdc-dialog__scrim {
              backdrop-filter: blur(5px);
            }
          ha-dialog {
            --vertical-align-dialog: center !important;
            --mdc-dialog-min-width: 50px;
            --mdc-dialog-max-width: 400px;
            --mdc-dialog-min-height: 350px !important;
            }
      content:
        type: vertical-stack
        cards:
          - type: custom:android-tv-card
            remote_id: media_player.android_tv_192_168_1_216
            keyboard_id: media_player.android_tv_192_168_1_216
            media_player_id: media_player.android_tv_192_168_1_216
            rows:
              - - power
                - home
                - play_pause
                - menu
              - - navigation_buttons
              - - back
                - volume_down
                - volume_up
                - keyboard
            custom_actions:
              - type: button
                name: power
                tap_action:
                  action: perform-action
                  perform_action: androidtv.adb_command
                  data:
                    command: POWER
                  target:
                    entity_id: media_player.android_tv_192_168_1_216
                icon: mdi:power
              - type: button
                name: back
                tap_action:
                  action: perform-action
                  perform_action: androidtv.adb_command
                  data:
                    command: BACK
                  target:
                    entity_id: media_player.android_tv_192_168_1_216
                icon: mdi:keyboard-backspace
              - type: button
                name: home
                tap_action:
                  action: perform-action
                  perform_action: androidtv.adb_command
                  data:
                    command: HOME
                  target:
                    entity_id: media_player.android_tv_192_168_1_216
                icon: mdi:home
              - type: button
                name: menu
                tap_action:
                  action: perform-action
                  perform_action: androidtv.adb_command
                  data:
                    command: MENU
                  target:
                    entity_id: media_player.android_tv_192_168_1_216
                icon: mdi:menu
              - type: button
                name: up
                tap_action:
                  action: perform-action
                  perform_action: androidtv.adb_command
                  data:
                    command: UP
                  target:
                    entity_id: media_player.android_tv_192_168_1_216
                hold_action:
                  action: repeat
                icon: mdi:chevron-up
              - type: button
                name: left
                tap_action:
                  action: perform-action
                  perform_action: androidtv.adb_command
                  data:
                    command: LEFT
                  target:
                    entity_id: media_player.android_tv_192_168_1_216
                hold_action:
                  action: repeat
                icon: mdi:chevron-left
              - type: button
                name: center
                tap_action:
                  action: perform-action
                  perform_action: androidtv.adb_command
                  data:
                    command: ENTER
                  target:
                    entity_id: media_player.android_tv_192_168_1_216
                icon: mdi:arrow-expand-all
              - type: button
                name: right
                tap_action:
                  action: perform-action
                  perform_action: androidtv.adb_command
                  data:
                    command: RIGHT
                  target:
                    entity_id: media_player.android_tv_192_168_1_216
                hold_action:
                  action: repeat
                icon: mdi:chevron-right
              - type: button
                name: down
                tap_action:
                  action: perform-action
                  perform_action: androidtv.adb_command
                  data:
                    command: DOWN
                  target:
                    entity_id: media_player.android_tv_192_168_1_216
                hold_action:
                  action: repeat
                icon: mdi:chevron-down
              - type: touchpad
                name: touchpad
                tap_action:
                  action: key
                  key: DPAD_CENTER
                up:
                  tap_action:
                    action: perform-action
                    perform_action: androidtv.adb_command
                    data:
                      command: UP
                    target:
                      entity_id: media_player.android_tv_192_168_1_216
                  hold_action:
                    action: repeat
                  name: up
                  type: button
                down:
                  tap_action:
                    action: perform-action
                    perform_action: androidtv.adb_command
                    data:
                      command: DOWN
                    target:
                      entity_id: media_player.android_tv_192_168_1_216
                  hold_action:
                    action: repeat
                  name: down
                  type: button
                left:
                  tap_action:
                    action: perform-action
                    perform_action: androidtv.adb_command
                    data:
                      command: LEFT
                    target:
                      entity_id: media_player.android_tv_192_168_1_216
                  hold_action:
                    action: repeat
                  name: left
                  type: button
                right:
                  tap_action:
                    action: perform-action
                    perform_action: androidtv.adb_command
                    data:
                      command: RIGHT
                    target:
                      entity_id: media_player.android_tv_192_168_1_216
                  hold_action:
                    action: repeat
                  name: right
                  type: button
                styles: |-
                  toucharea {
                    background-image: url("/local/fingerprint.png");
                    background-size: 150px;
                    background-repeat: no-repeat;
                    background-position: center;
                    opacity: 0.5;
                    box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.9);;
                    height: 160px;
                    width: 160px;
                  }
                double_tap_action:
                  action: key
                  key: menu
            styles: |-
              remote-button {
                --size: 32px;
                color: grey;
                border-width: 3px;;
                box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.9);;
                border-radius: 50%;;
                backgound-color: black;;
                background-opacity: 50%;;
                padding: 8px;;
              }
            card_mod:
              style: |
                }    ha-card {
                margin-bottom: 20px;    }
card_mod:
  style:
    mmp-shortcuts $:
      div.mmp-shortcuts__buttons mmp-button.mmp-shortcuts__button div: |
        img {
          height: 50% !important;
        }
```

**Comment by Nerwyn** [comment]
What exactly is inconsistent?

**Comment by Nerwyn** [comment]
It looks like you didn't click the update old config button for the first popup remote. Here they are cleaned up a little bit.

```yaml
type: vertical-stack
cards:
  - type: custom:android-tv-card
    remote_id: media_player.android_tv_192_168_1_216
    keyboard_id: media_player.android_tv_192_168_1_216
    media_player_id: media_player.android_tv_192_168_1_216
    rows:
      - - power
        - home
        - menu
      - - touchpad
      - - back
        - keyboard
    custom_actions:
      - type: button
        name: power
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: POWER
          target:
            entity_id: media_player.android_tv_192_168_1_216
        icon: mdi:power
      - type: button
        name: back
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: BACK
          target:
            entity_id: media_player.android_tv_192_168_1_216
        icon: mdi:keyboard-backspace
      - type: button
        name: home
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: HOME
          target:
            entity_id: media_player.android_tv_192_168_1_216
        icon: mdi:home
      - type: button
        name: menu
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: MENU
          target:
            entity_id: media_player.android_tv_192_168_1_216
        icon: mdi:menu
      - type: button
        name: up
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: UP
          target:
            entity_id: media_player.android_tv_192_168_1_216
        hold_action:
          action: repeat
        icon: mdi:chevron-up
      - type: button
        name: left
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: LEFT
          target:
            entity_id: media_player.android_tv_192_168_1_216
        hold_action:
          action: repeat
        icon: mdi:chevron-left
      - type: button
        name: center
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: ENTER
          target:
            entity_id: media_player.android_tv_192_168_1_216
        icon: mdi:arrow-expand-all
      - type: button
        name: right
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: RIGHT
          target:
            entity_id: media_player.android_tv_192_168_1_216
        hold_action:
          action: repeat
        icon: mdi:chevron-right
      - type: button
        name: down
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: DOWN
          target:
            entity_id: media_player.android_tv_192_168_1_216
        hold_action:
          action: repeat
        icon: mdi:chevron-down
      - type: touchpad
        name: touchpad
        tap_action:
          action: key
          key: DPAD_CENTER
        up:
          tap_action:
            action: perform-action
            perform_action: androidtv.adb_command
            data:
              command: UP
            target:
              entity_id: media_player.android_tv_192_168_1_216
          hold_action:
            action: repeat
          name: up
          type: button
        down:
          tap_action:
            action: perform-action
            perform_action: androidtv.adb_command
            data:
              command: DOWN
            target:
              entity_id: media_player.android_tv_192_168_1_216
          hold_action:
            action: repeat
          name: down
          type: button
        left:
          tap_action:
            action: perform-action
            perform_action: androidtv.adb_command
            data:
              command: LEFT
            target:
              entity_id: media_player.android_tv_192_168_1_216
          hold_action:
            action: repeat
          name: left
          type: button
        right:
          tap_action:
            action: perform-action
            perform_action: androidtv.adb_command
            data:
              command: RIGHT
            target:
              entity_id: media_player.android_tv_192_168_1_216
          hold_action:
            action: repeat
          name: right
          type: button
        styles: |-
          toucharea {
            background-image: url("/local/fingerprint.png");
            background-size: 150px;
            background-repeat: no-repeat;
            background-position: center;
            opacity: 0.5;
            box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.9);;
            height: 160px;
            width: 160px;
          }
        double_tap_action:
          action: key
          key: menu
    styles: |-
      remote-button {
        --size: 32px;
        color: grey;
        border-width: 3px;;
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.9);;
        border-radius: 50%;;
        backgound-color: black;;
        background-opacity: 50%;;
        padding: 8px;;
      }
    card_mod:
      style: |
        ha-card {
          margin-bottom: 20px;
        }
  - type: custom:android-tv-card
    remote_id: media_player.android_tv_192_168_1_216
    keyboard_id: media_player.android_tv_192_168_1_216
    media_player_id: media_player.android_tv_192_168_1_216
    rows:
      - - power
        - home
        - play_pause
        - menu
      - - navigation_buttons
      - - back
        - volume_down
        - volume_up
        - keyboard
    custom_actions:
      - type: button
        name: power
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: POWER
          target:
            entity_id: media_player.android_tv_192_168_1_216
        icon: mdi:power
      - type: button
        name: back
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: BACK
          target:
            entity_id: media_player.android_tv_192_168_1_216
        icon: mdi:keyboard-backspace
      - type: button
        name: home
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: HOME
          target:
            entity_id: media_player.android_tv_192_168_1_216
        icon: mdi:home
      - type: button
        name: menu
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: MENU
          target:
            entity_id: media_player.android_tv_192_168_1_216
        icon: mdi:menu
      - type: button
        name: up
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: UP
          target:
            entity_id: media_player.android_tv_192_168_1_216
        hold_action:
          action: repeat
        icon: mdi:chevron-up
      - type: button
        name: left
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: LEFT
          target:
            entity_id: media_player.android_tv_192_168_1_216
        hold_action:
          action: repeat
        icon: mdi:chevron-left
      - type: button
        name: center
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: ENTER
          target:
            entity_id: media_player.android_tv_192_168_1_216
        icon: mdi:arrow-expand-all
      - type: button
        name: right
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: RIGHT
          target:
            entity_id: media_player.android_tv_192_168_1_216
        hold_action:
          action: repeat
        icon: mdi:chevron-right
      - type: button
        name: down
        tap_action:
          action: perform-action
          perform_action: androidtv.adb_command
          data:
            command: DOWN
          target:
            entity_id: media_player.android_tv_192_168_1_216
        hold_action:
          action: repeat
        icon: mdi:chevron-down
    styles: |-
      remote-button {
        --size: 32px;
        color: grey;
        border-width: 3px;;
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.9);;
        border-radius: 50%;;
        backgound-color: black;;
        background-opacity: 50%;;
        padding: 8px;;
      }
    card_mod:
      style: |
        ha-card {
          margin-bottom: 20px;
        }
```

**Comment by madjetey** [comment]
Same issue with the updated configs posted.  Layout buttons don't respond consistently.  In the 2nd vertical card, the volume buttons don't respond.  Going to try defining actions but it doesn't seem optimal.

**Comment by Nerwyn** [comment]
I don't understand what you mean by "Layout buttons don't respond consistently".

It looks like you're using Android ADB / Fire TV instead of the Android TV remote API. You should set the global platform to `Fire TV` and delete the unneeded custom actions. The center command should be `CENTER` and according to [this list](https://www.home-assistant.io/integrations/androidtv/#remote), there are no separate commands for play, pause, or play_pause for Fire TV / ADB. Sending a play/pause/play_pause command to the ADB media player may work.

Were you previously on the v4 beta? I see what looks like some upgrade artifacts/mistakes from when I was still fixing the old config upgrade process in your config. Try this config:

```yaml
type: custom:android-tv-card
remote_id: remote.android_tv_192_168_1_216
keyboard_id: remote.android_tv_192_168_1_216
media_player_id: media_player.android_tv_192_168_1_216
rows:
  - - power
    - home
    - play_pause
    - menu
  - - touchpad
  - - back
    - volume_down
    - volume_up
    - keyboard
custom_actions:
  - type: touchpad
    name: touchpad
    tap_action:
      action: key
      key: CENTER
    up:
      tap_action:
        action: perform-action
        perform_action: androidtv.adb_command
        data:
          command: UP
      hold_action:
        action: repeat
    down:
      tap_action:
        action: perform-action
        perform_action: androidtv.adb_command
        data:
          command: DOWN
      hold_action:
        action: repeat
    left:
      tap_action:
        action: perform-action
        perform_action: androidtv.adb_command
        data:
          command: LEFT
      hold_action:
        action: repeat
    right:
      tap_action:
        action: perform-action
        perform_action: androidtv.adb_command
        data:
          command: RIGHT
      hold_action:
        action: repeat
    styles: |-
      toucharea {
        background-image: url("/local/fingerprint.png");
        background-size: 150px;
        background-repeat: no-repeat;
        background-position: center;
        opacity: 0.5;
        box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.9);;
        height: 160px;
        width: 160px;
      }
  - type: button
    name: play_pause
    tap_action:
      action: perform-action
      perform_action: media_player.media_play_pause
      target: {}
    icon: mdi:play
    value_attribute: supported_features
styles: |-
  remote-button {
    --size: 32px;
    color: grey;
    border-width: 3px;;
    box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.9);;
    border-radius: 50%;;
    backgound-color: black;;
    background-opacity: 50%;;
    padding: 8px;;
  }
card_mod:
  style: |
    ha-card {
      margin-bottom: 20px;
    }
```
