### ISSUE TITLE
Custom element doesn't exist: universal-remote-card

### ISSUE THREAD

**Issue by romquenin** [Nerwyn/android-tv-card#135]
- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

***Release with the issue:*** 4.0.3

***Last working release (if known):*** 3.9.4

***Browser and Operating System:*** Chrome and Android's Mobile APP 

***Description of problem:*** Custom element doesn't exist: universal-remote-card

**Your Full Remote Config**

```
- url: /hacsfiles/android-tv-card/universal-remote-card.min.js
  type: module
```

```        
      - type: custom:universal-remote-card
        remote_id: remote.android_tv
        media_player_id: media_player.android_tv
        rows:
          - - power
          - - back
            - home
            - tv
          - - volume_down
            - volume_mute
            - volume_up
          - - rewind
            - play_pause
            - fast_forward
        # volume_row: slider
          - - touchpad
          - - keyboard
            - search
          - - netflix
            - primevideo
            - disney
            - youtube
            - plex
        custom_actions:
          - type: button
            # icon: mdi:power-cycle
            tap_action:
              action: perform-action
              perform_action: media_player.play_media
              data:
                media_content_type: app
                media_content_id: com.ottplay.ottplay
              target:
                entity_id: media_player.android_tv

```

**Additional information:**
![Capture d’écran 2024-09-11 160217](https://github.com/user-attachments/assets/e99c5b21-395a-4226-8ad1-e7b615394c26)
![Capture d’écran 2024-09-11 161335](https://github.com/user-attachments/assets/af2c0382-efbc-4437-87ed-5a370a262554)
