### ISSUE TITLE
Many Buttons Invisible

### ISSUE THREAD

**Issue by schniepp** [Nerwyn/android-tv-card#137]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
4.0.4

**Last working release (if known):**

**Browser and Operating System:**
Firefox (Chrome, Chromium, Vivaldi), Ubuntu

**Description of problem:**
Several buttons are invisible (dmap, netflix, touchpad, slider, pause, fast_forward). When I hover over them, the toolboxtext hint shows up, so they are there in principle. Interestingly, the hinted text will not say the name of the button (like "Play", which it does for the visible buttons), but only "row-5". 

**Javascript errors shown in the web inspector (if applicable):**
There are actually a huge number of errors. I am not entirely sure which ones are relevant. I just opened this log for the first time. 
```

```

**Your Full Remote Config**

```yaml
type: custom:android-tv-card
platform: Roku
remote_id: remote.roku_ultra
media_player_id: media_player.roku_ultra
title: Roku Ultra
autofill_entity_id: true
rows:
  - - home
    - info
  - - netflix
    - youtube
  - - volume_buttons
  - - dpad
  - - back
    - rewind
    - play
    - pause
    - fast_forward
    - keyboard
  - - netflix
    - disney
    - primevideo
  - - touchpad
    - slider
  - - navigation_buttons
custom_actions: []
haptics: true
```

**Additional information:**
