### ISSUE TITLE
Swipe when KODI is playing does not work.

### ISSUE THREAD

**Issue by Phyxsius7** [Nerwyn/android-tv-card#143]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser

**Release with the issue:**
v4.0.6

**Last working release (if known):**
did not use previous vesions

**Browser and Operating System:**
Andriod 14 with Home assistant app 2024.9.4-full
Windows 11 with Chrome 129.0.6668.90

Used this on my Andriod phone and also on my laptop using touch screen and mouse pad running Chrome browser.
Results is the same.

**Description of problem:**
Navigation with swipe pad does work in KODI menu navigation but it does not work for video scrubbing.

steps to reproduce:

1. start a video content with KODI
2. swipe left, right, up or down.
result: no responds responds
exception: dubbel tap does respond by exiting (not stopping) the playback. While playback continues navigation throught KODI menu works as expected.

expected result:

- swipe left > jump 10 sec. back in playback. (amount can be modified in KODI settings)
- swipe right> jump 10 sec. forward in playback (amount can be modified in KODI settings)
- swipe up > jump to next video content
- swipe down > jump back to beginning of current content

**Javascript errors shown in the web inspector (if applicable):**
No errors

**Full Remote Config**

```yaml
type: custom:android-tv-card
keyboard_id: media_player.kodi
media_player_id: media_player.192_168_1_22
platform: Kodi
rows:
  - - back
    - home
    - menu
  - - info
    - play_pause
  - - - volume_buttons
    - touchpad
    - - textbox
      - null
      - search
custom_actions:
  - type: touchpad
    name: touchpad
    tap_action:
      action: perform-action
      perform_action: kodi.call_method
      data:
        method: Input.Select
    up:
      tap_action:
        action: perform-action
        perform_action: kodi.call_method
        data:
          method: Input.Up
      hold_action:
        action: repeat
      styles: ""
    down:
      tap_action:
        action: perform-action
        perform_action: kodi.call_method
        data:
          method: Input.Down
      hold_action:
        action: repeat
    left:
      tap_action:
        action: perform-action
        perform_action: kodi.call_method
        data:
          method: Input.Left
      hold_action:
        action: repeat
    right:
      tap_action:
        action: perform-action
        perform_action: kodi.call_method
        data:
          method: Input.Right
      hold_action:
        action: repeat
    styles: |-
      toucharea {
        height: 200px;
        background-image: url("https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Kodi-logo-Thumbnail-light-transparent.png/600px-Kodi-logo-Thumbnail-light-transparent.png?20141126003611");
        background-size: contain;
        background-repeat: no-repeat;
        background-position: center;
        opacity: 1.0;;
      }
    hold_action:
      action: perform-action
      perform_action: kodi.call_method
      data:
        method: Input.ContextMenu
    double_tap_action:
      action: perform-action
      perform_action: kodi.call_method
      data:
        method: Input.Back
custom_icons: []
```
