### ISSUE TITLE
Roku default play/pause

### ISSUE THREAD

**Issue by mateusfn98** [Nerwyn/android-tv-card#149]
The default play button for Roku is a play/pause function.
![image](https://github.com/user-attachments/assets/5dfe7d25-9d8f-496b-8419-58debe925dc7)

In the code:
https://github.com/Nerwyn/android-tv-card/blob/main/src/models/maps/roku/defaultKeys.ts
```
        {
		type: 'button',
		name: 'play',
		tap_action: { action: 'key', key: 'play' },
		icon: 'mdi:play',
	},
```
Change icon for
```
icon: mdi:play-pause
```

I've made a custom button for a workaround.
```
type: button
name: play/pause
tap_action:
  action: key
  key: play
icon: mdi:play-pause
```
Also, you could change the default roku layout for something like this:
![image](https://github.com/user-attachments/assets/70fd08de-1393-444a-b630-dc77609b8a97)

Is a good layout for those who used to use Roku remote.
```
rows:
  - - power
    - back
    - home
  - - textbox
    - dpad
    - delete
  - - reverse
    - play/pause
    - forward
  - - replay
    - info
```

**Comment by Nerwyn** [comment]
To keep it consistent across platforms, I'll make two more copies of the `play` key, but name them `pause` and `play_pause` with the matching icons.

**Comment by mateusfn98** [comment]
Also, for matching roku remote there is another thing:
```
  - type: button
    name: roku_info
    icon: mdi:asterisk
    tap_action:
      action: key
      key: info
```

Because the info button in the roku remote is an asterisk, but just a detail.
