### ISSUE TITLE
Alternate Keyboard Send Modes like Kodi

### ISSUE THREAD

**Issue by Nerwyn** [Nerwyn/android-tv-card#15]
**Is your feature request related to a problem? Please describe.**
Keyboard support for alternate platforms, namely Kodi as there is a path forward for that.

**Describe the solution you'd like**
A separate input option like `keyboard_mode` which defaults to Android TV but can be set to other values like Kodi.

**Describe alternatives you've considered**
NA

**Additional context**
[Community forum discussion.](https://community.home-assistant.io/t/android-tv-card-a-tv-card-fork-for-android-tv/585089/44?u=nerwyn)

[The Kodi JSON-RPC API can be used to send text](https://kodi.wiki/view/JSON-RPC_API/v13#Input.SendText) using the Home Assistant integration as described [here](https://www.home-assistant.io/integrations/kodi/#service-kodicall_method).

**Comment by Nerwyn** [comment]
RC - https://github.com/Nerwyn/android-tv-card/releases/tag/v2.1.0-dev.007

**Comment by houser42** [comment]
This new Kodi Keyboard is great and very useful!
Is it also possible to use the two new text commands in separate buttons out side of the touchpad?
If so, how please?

**Comment by Nerwyn** [comment]
Good to hear that it's working!

Yes, it's the same as the `textbox` and `search` buttons as before, no touchpad required. Just create those buttons anywhere.

**Comment by houser42** [comment]
I have never created a command that is specific to this card outside of it.
I see nothing in the docs for this. Would appreciate a hint? Many thanks!

**Comment by Nerwyn** [comment]
Please look at the README, it explains how to do this.

Old rows method:
```yaml
keyboard_id: media_player.kodi
keyboard_mode: KODI
keyboard_row:
  - textbox
  - search
custom_keys:
  search:
    icon: mdi:kodi # This is just to change the icon since the default is Google Assistant
    key: SEARCH
```

New rows array method as of v2
```yaml
keyboard_id: media_player.kodi
keyboard_mode: KODI
rows:
  - - textbox
     - search
custom_keys:
  search:
    icon: mdi:kodi # This is just to change the icon since the default is Google Assistant
    key: SEARCH
```

**Comment by Nerwyn** [comment]
Added in [v2.1.0](https://github.com/Nerwyn/android-tv-card/releases/tag/v2.1.0)

**Comment by houser42** [comment]
Thaks again. I guess I did it about right.
Is there a way to change the size of the icon? Card Mod maybe?

**Comment by Nerwyn** [comment]
Yes. You may also want to increase the padding around rows and columns to account for the larger icons.
```yaml
card_mod:
  style: |
    toucharea {
      background-image: url("https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Kodi-logo-Thumbnail-light-transparent.png/600px-Kodi-logo-Thumbnail-light-transparent.png?20141126003611");
      background-size: contain;
      background-repeat: no-repeat;
      background-position: center;
      opacity: 1.0;
    }
    ha-icon-button[title="search"] > ha-icon {
      width: 80px;
      height: 80px;
    }
    .column {
      padding: 24px
    }
```
https://developer.mozilla.org/en-US/docs/Web/CSS/padding

**Comment by houser42** [comment]
I am probably misunderstanding something.. but the icon is controlled this way but the size of the button is not.
Sorry my css is not great.
I am using this in a grid card and whatever I do with css, the height of this button makes the entire grid card to big in terms of height. I'll slave away on this and it is not a showstopper, but understanding how the buttons of this card are used  outside and controlled via card mod would be great.

**Comment by Nerwyn** [comment]
No you're right. I just pushed out a small update that improves the `ha-icon-button` css so it's more card-mod friendly. Update to the latest version and try this:

```yaml
card_mod:
  style: |
    toucharea {
      background-image: url("https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Kodi-logo-Thumbnail-light-transparent.png/600px-Kodi-logo-Thumbnail-light-transparent.png?20141126003611");
      background-size: contain;
      background-repeat: no-repeat;
      background-position: center;
      opacity: 1.0;
    }
      
    ha-icon-button[title="search"],
    ha-icon-button[title="search"] > ha-icon {
      color: rgb(9, 179, 232);     
      height: 100px;
      width: 100px;
    }
```

**Comment by houser42** [comment]
Thanks.
So I updated to V2.1.2, I that the version you meant? Or is there a beta?
I still can not make the button have the height I want. It still makes the grid row height fat.

**Comment by houser42** [comment]
Sure. Here is the grid of 7buttons:
```
square: false
type: grid
cards:
  - show_name: true
    show_icon: false
    type: button
    tap_action:
      action: call-service
      service: kodi.call_method
      data:
        method: Input.ExecuteAction
        action: bigstepback
      target:
        entity_id: media_player.kodi
    name: < 10m
    icon: mdi:skip-backward
    icon_height: 24px
  - show_name: true
    show_icon: false
    type: button
    tap_action:
      action: call-service
      service: kodi.call_method
      data:
        method: Input.ExecuteAction
        action: stepback
      target:
        entity_id: media_player.kodi
    name: < 10s
    icon: mdi:skip-previous
    icon_height: 24px
  - show_name: true
    show_icon: false
    type: button
    tap_action:
      action: call-service
      service: kodi.call_method
      data:
        method: Input.ExecuteAction
        action: stepforward
      target:
        entity_id: media_player.kodi
    icon: mdi:skip-next
    icon_height: 24px
    name: 10s >
  - show_name: true
    show_icon: false
    type: button
    tap_action:
      action: call-service
      service: kodi.call_method
      data:
        method: Input.ExecuteAction
        action: bigstepforward
      target:
        entity_id: media_player.kodi
    name: 10m >
    icon: mdi:skip-forward
    icon_height: 24px
  - type: custom:android-tv-card
    keyboard_id: media_player.kodi
    keyboard_mode: KODI
    rows:
      - textbox
    custom_keys:
      search:
        icon: mdi:text-box
        icon_height: 24px
        key: textbox
      card_mod: null
      style: |
        toucharea {
        }
          
        ha-icon-button[title="textbox"],
        ha-icon-button[title="textbox"] > ha-icon {
          color: rgb(9, 179, 232);     
          height: 24px;
          width: 24px;
        }
  - type: custom:android-tv-card
    keyboard_id: media_player.kodi
    keyboard_mode: KODI
    rows:
      - search
    custom_keys:
      search:
        icon: mdi:text-search
        icon_height: 24px
        key: SEARCH
    card_mod:
      style: |
        toucharea {
        }
          
        ha-icon-button[title="search"],
        ha-icon-button[title="search"] > ha-icon {);     
          height: 24px;
          width: 24px;
        }
  - show_name: false
    show_icon: true
    type: button
    tap_action:
      action: navigate
      navigation_path: /kodi-swipe-1
    icon: mdi:dots-horizontal-circle-outline
columns: 7
```

**Comment by Nerwyn** [comment]
It's because your config has typos:
- In button 5 `card_mod` is one level too deep and is set to `null`
- In button 6 you have an erroneous `);` at the end of your `ha-icon` selector
- You don't need the `toucharea` selector and can safely delete it from both buttons

**Comment by houser42** [comment]
Thanks so much! I am still a newbie on HA and YAML...
That fixed the icon errors but not the height of the button row. 
The only way to get the proper height of the button row is to remove the two new text buttons.
But I can live with it ;)

**Comment by houser42** [comment]
The only way to get the proper height of the button row is to remove the two new text buttons.

This is with the text buttons:
<img width="396" alt="1 with textbuttons" src="https://github.com/Nerwyn/android-tv-card/assets/15192440/c4ac1878-9569-47f7-8ba9-2000a17bddc8">

This is the height when I remove the two text buttons from this card:
<img width="360" alt="2 without textbuttons" src="https://github.com/Nerwyn/android-tv-card/assets/15192440/219769f9-7695-48ee-a1b8-3405f519fd2e">

I can live with it, but let me know if you see the same please?

**Comment by Nerwyn** [comment]
It looks like there are several child elements which still have width and height of 48px.
<img width="1145" alt="image" src="https://github.com/Nerwyn/android-tv-card/assets/43071698/91fad450-114d-4f74-95d7-278921270636">
I'll have to play around with the CSS later to try to make them inherit height instead. Which may not be possible as they are autogenerated by Home Assistant when the `ha-icon-button` element is created.

**Comment by Nerwyn** [comment]
@houser42 as I thought, I wasn't able to modify the CSS of the auto-generated elements within `ha-icon-button`. BUT I was able to safely remove `min-height` from rows and columns which should fix your issue. Rows and columns still have padding but you can change it using card-mod like so:

```yaml
  - type: custom:android-tv-card
    keyboard_id: media_player.kodi
    keyboard_mode: KODI
    rows:
      - textbox
    custom_keys:
      search:
        icon: mdi:text-box
        icon_height: 24px
        key: textbox
    card_mod:
      style: |
        ha-icon-button[title="textbox"],
        ha-icon-button[title="textbox"] > ha-icon {
          color: rgb(9, 179, 232);     
          height: 24px;
          width: 24px;
        }
        .row {
          padding: 8px; # Whatever you want
        }
```
<img width="252" alt="image" src="https://github.com/Nerwyn/android-tv-card/assets/43071698/9a9400ad-de7f-418a-bc08-7ae504f3d7bf">
