### ISSUE TITLE
volume doesn't work + question about icon

### ISSUE THREAD

**Issue by jboesh** [Nerwyn/android-tv-card#16]
Hi, 2 questions:

**1.** I'm having trouble using the volume buttons not working for me. Do you have any idea what this could be due to? other buttons work well! Like the volume slider.
If I call the same media player in another lovelace card, the volume buttons work:

![image](https://github.com/Nerwyn/android-tv-card/assets/71582854/b707a000-f5f9-4183-90c5-ec89f907c754)

The code which doesn't work with volume:

```
type: custom:android-tv-card
remote_id: remote.chromecastwoonkamer
media_player_id: media_player.samsung_au7100_70_tv
title: TVWoonkamer
rows:
  - - back
    - power
    - home
  - - keyboard
    - search
    - info
  - - volume_buttons
  - - navigation_buttons
  - - netflix
    - youtube
    - disney
    - spotify
    - videoland
  - - previous
    - rewind
    - play_pause
    - fast_forward
    - next
custom_sources:
  videoland:
    icon: mdi:television-classic
    source: videoland-v2://
```

**2.** Another question about the custom sources part.
I have added "videoland" to it, but there is no icon that I can find en match here: https://simpleicons.org/?q=vide

It is possible to add a text? only the "V" is enough to know what the button does.
Otherwise it is possible to add a URL to the image? that can be used as icon? like this:

```
      - type: picture
        image: https://assets.televizier.nl/upload/w/t/Wat-is-Videoland.jpg
        tap_action:
          action: call-service
          service: remote.turn_on
          data:
            activity: videoland-v2://

```

thanks!

**Comment by Nerwyn** [comment]
1. The volume buttons use the remote entity while the slider uses the media player entity. Is your Android TV configured to forward volume commands to your TV via HDMI-CEC? I personally use custom keys to remap volume up, down, and mute to my AV receiver. If not create custom keys for volume up, down, and mute to remap them to your media player instead.
```yaml
custom_keys:
  volume_down:
    service: media_player.volume_down
    service_data:
      entity_id: media_player.samsung_au7100_70_tv
  volume_mute:
    service: media_player.volume_mute
    service_data:
      entity_id: media_player.samsung_au7100_70_tv
  volume_up:
    service: media_player.volume_up
    service_data:
      entity_id: media_player.samsung_au7100_70_tv
```

2. No support for text, but you could set the icon to `mdi:alpha-v`. I also messed around with [card-mod](https://github.com/thomasloven/lovelace-card-mod) and was able to set the button to an image (look for transparent PNGs for icons using this method rather than JPGs, the latter have compression artifacts and look terrible). Try this:
```yaml
custom_sources:
  videoland:
    source: videoland-v2://
card_mod:
  style: |
    ha-icon-button[title="videoland"] {
      background-image: url(https://cdn6.aptoide.com/imgs/3/c/8/3c8d26f1af6306c09b9cfa24fe679949_icon.png);
      background-repeat: no-repeat;
      background-size: contain;
    }
```
