### ISSUE TITLE
How to get the text box content?

### ISSUE THREAD

**Issue by Ainndy** [Nerwyn/android-tv-card#160]
Hello, I want to get the content of the text box and send it to my TV via HTTP GET, but I don't know how to get the content of the text box.  (For example, 123456) Thanks.
![屏幕截图 2024-11-18 220133](https://github.com/user-attachments/assets/eaf2dffa-4080-4b3e-9b00-fff0398fb4f3)

**Comment by ngem1** [comment]
It would be great if you could customise what happens when you enter text via keyboard. I have altered the Apple TV integration so I can use the pyatv command 'keyboard.text_set'.

I've got a helper input_text entity that feeds into the action below:

`target:
  entity_id: remote.lounge_apple_tv
data:
  command:
    - keyboard.text_set {{ states('input_text.lounge_apple_tv_keyboard') }}
action: remote.send_command`

If I could grab the text in the keyboard interaction of android-tv-card or if I could alter the command sent on entering text in the keyboard interaction, I could send text to Apple TV through android-tv-card.

**Comment by ngem1** [comment]
It would be great if you could customise what happens when you enter text via keyboard. I have altered the Apple TV integration so I can use the pyatv command `keyboard.text_set`.

I've got a helper input_text entity that feeds into the action below:

```
alias: Lounge Apple TV Input Keyboard
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_text.lounge_apple_tv_keyboard
conditions: []
actions:
  - target:
      entity_id: remote.lounge_apple_tv
    data:
      command:
        - keyboard.text_set {{ states('input_text.lounge_apple_tv_keyboard') }}
    action: remote.send_command
mode: single
```

If I could grab the text in the keyboard interaction of android-tv-card or if I could alter the command sent on entering text in the keyboard interaction, I could send text to Apple TV through android-tv-card.
