### ISSUE TITLE
LG webOS Keyboard Support

### ISSUE THREAD

**Issue by Nerwyn** [Nerwyn/android-tv-card#161]
**Is your feature request related to a problem? Please describe.**
There may be a way to add keyboard support to the LG webOS platform.

**Describe the solution you'd like**
Sending text:
```yaml
action: perform-action
perform_action: webostv.command
data:
  command: com.webos.service.ime/insertText
  payload:
    text: text
    replace: true # disable force cursor to end like Kodi
target:
  entity_id: media_player.lg_webos_smart_tv
```

Enter:
```yaml
action: perform-action
perform_action: webostv.command
data:
  command: com.webos.service.ime/sendEnterKey
target:
  entity_id: media_player.lg_webos_smart_tv
```

**Describe alternatives you've considered**
NA

**Additional context**
I should also consider adding some more webOS default keys using the list provided in [the integration docs](https://www.home-assistant.io/integrations/webostv/#action-webostvcommand).

Is there a way to add global search using this?

I don't have a webOS TV, I'll need testers!
