### ISSUE TITLE
Misaligned dpad

### ISSUE THREAD

**Issue by amitlalani** [Nerwyn/android-tv-card#166]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**

**Last working release (if known):** N/A

**Browser and Operating System:**
Home assistant android app on Samsung Galaxy 23. My partner has the same setup and sees the same issue.

**Description of problem:**
Misaligned dpad, as you can see in the image, its skewed to the right. I used example 13 as a foundation which works fine. When I add 2 rows above it, the issue started. I am not well versed in CSS to understand why. Hope you can help. 

<img width="450" alt="Screenshot 2024-12-12 at 12 56 55" src="https://github.com/user-attachments/assets/a6deb9a0-9fb6-4d34-bdd8-f2c2c4358794" />

**Javascript errors shown in the web inspector (if applicable):** N/A

**Your Full Remote Config**

```yaml
type: custom:android-tv-card
remote_id: remote.sony_kd_65xf9005
rows:
  - - power
  - - netflix
    - jellyfin
    - disney
  - - volume_buttons
  - - navigation_buttons
  - - back
    - home
    - n1
  - - rewind
    - play
    - pause
    - fast_forward
custom_actions:
  - type: button
    name: center
    tap_action:
      action: key
      key: DpadCenter
    icon: mdi:checkbox-blank-circle
    styles: |-
      :host {
        --icon-color: rgb(94, 94, 94);
        --size: 200px;
        background: rgb(31, 31, 31);
        border-radius: 200px;
        margin: -70px;
        padding: 70px;
      }
  - type: button
    name: up
    tap_action:
      action: key
      key: Up
    hold_action:
      action: repeat
    icon: mdi:chevron-up
    styles: |-
      :host {
        --icon-color: rgb(197, 199, 197);
        z-index: 2;
        top: 25px;
        height: 90px;
        width: 300px;
      }
  - type: button
    name: down
    tap_action:
      action: key
      key: Down
    hold_action:
      action: repeat
    icon: mdi:chevron-down
    styles: |-
      :host {
        --icon-color: rgb(197, 199, 197);
        z-index: 2;
        bottom: 25px;
        height: 90px;
        width: 300px;
      }
  - type: button
    name: left
    tap_action:
      action: key
      key: Left
    hold_action:
      action: repeat
    icon: mdi:chevron-left
    styles: |-
      :host {
        --icon-color: rgb(197, 199, 197);
        z-index: 2;
        left: 30px;
        height: 170px;
        width: 90px;
      }
  - type: button
    name: right
    tap_action:
      action: key
      key: Right
    hold_action:
      action: repeat
    icon: mdi:chevron-right
    styles: |-
      :host {
        --icon-color: rgb(197, 199, 197);
        z-index: 2;
        right: 30px;
        height: 170px;
        width: 90px;
      }
platform: Sony BRAVIA

```

**Additional information:**

**Comment by Nerwyn** [comment]
You didn't include the column styles in your card config, as shown in [the Google TV navigation buttons example](https://github.com/Nerwyn/android-tv-card?tab=readme-ov-file#example-13), which is why the Google TV style navigation buttons doesn't align correctly on smaller displays.

Add this to your overall CSS styles.

```css
#row-4, #row-5, #row-6 {
  justify-content: center;
}
```
