### ISSUE TITLE
Double tap on touchpad not working on 4.3

### ISSUE THREAD

**Issue by viseniv** [Nerwyn/android-tv-card#167]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser
- [X] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**

**Last working release (if known):4.2.1

**Browser and Operating System:**

Home Assistant Companion App

**Description of problem:**

I have created a custom action for double tap on the touchpad funcionality. 
This action is not triggered anymore on 4.3 if i roll back to 4.2.1 with the same config is working again. 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Remote Config**

```yaml
type: custom:state-switch
entity: hash
default: p4
states:
  p2:
    type: custom:android-tv-card
    custom_actions:
      - type: slider
        name: slider2
        range:
          - 0
          - 0.2
        step: 0.01
        value_attribute: volume_level
        tap_action:
          action: perform-action
          perform_action: media_player.volume_set
          data:
            volume_level: "{{ value | float }}"
        entity_id: media_player.ht_zf9
        icon: mdi:volume-medium
      - type: touchpad
        name: touchpad
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "74063740"
            command: OK
        up:
          tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "74063740"
              command: DirectionUp
          hold_action:
            action: repeat
          icon: mdi:arrow-up-bold
          multi_tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "74063740"
              command: ChannelUp
        down:
          tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "74063740"
              command: DirectionDown
          hold_action:
            action: repeat
          icon: mdi:arrow-down-bold
          multi_tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "74063740"
              command: ChannelDown
        left:
          tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "74063740"
              command: DirectionLeft
          hold_action:
            action: repeat
          icon: mdi:arrow-left-bold
        right:
          tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "74063740"
              command: DirectionRight
          hold_action:
            action: repeat
          icon: mdi:arrow-right-bold
        icon: mdi:record
        double_tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "74063740"
            command: Back
        hold_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "74063740"
            command: Exit
      - type: button
        name: button nada
        tap_action:
          action: none
      - type: button
        name: menu kodi
        icon: mdi:menu
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: C
        hold_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: S
      - type: button
        name: pc stop
        icon: mdi:stop
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target: null
          device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: X
      - type: button
        name: pc pause play
        icon: mdi:play-pause
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: Pause
      - type: button
        name: pc info
        icon: mdi:information-outline
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: Info
        hold_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: O
      - type: button
        name: harmony kodi
        icon: mdi:kodi
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: Win+4
      - type: button
        name: mute
        icon: mdi:volume-off
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: Mute
            device: "55138018"
      - type: button
        name: Navigate LG
        icon: phu:lg
        styles: |-
          :host {
            --icon-color: rgb(220, 20, 60);
          }
        tap_action:
          action: navigate
          navigation_path: "#p2"
      - type: button
        name: Navigate Sony
        icon: si:sony
        tap_action:
          action: navigate
          navigation_path: "#p3"
      - type: button
        name: Navigate Windows
        icon: mdi:microsoft-windows
        tap_action:
          action: navigate
          navigation_path: "#p4"
      - type: button
        name: Home LG
        icon: mdi:home
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: Home
            device: "74063740"
      - type: button
        name: Settings LG
        icon: mdi:menu
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: Settings
            device: "74063740"
      - type: button
        name: PowerOn LG
        icon: mdi:power-on
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: PowerOn
            device: "74063740"
      - type: button
        name: PowerOff LG
        icon: mdi:power-off
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: PowerOff
            device: "74063740"
      - type: button
        name: Stop LG
        icon: mdi:stop
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: Stop
            device: "74063740"
      - type: button
        name: Pause LG
        icon: mdi:play-pause
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: Pause
            device: "74063740"
      - type: button
        name: Play LG
        icon: mdi:play
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: Play
            device: "74063740"
      - type: button
        name: Picture Mode LG
        icon: mdi:image-area-close
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: PictureMode
            device: "74063740"
      - type: button
        name: Mute LG
        icon: mdi:volume-off
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: Mute
            device: "74063740"
      - type: button
        name: VolumeMinus LG
        icon: mdi:volume-minus
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: VolumeDown
            device: "74063740"
      - type: button
        name: VolumeUp LG
        icon: mdi:volume-plus
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: VolumeUp
            device: "74063740"
    platform: Kodi
    remote_id: remote.comedor
    keyboard_id: media_player.ht_zf9
    media_player_id: media_player.ht_zf9
    rows:
      - - PowerOff LG
        - PowerOn LG
      - - Navigate LG
        - Navigate Sony
        - Navigate Windows
      - - Home LG
        - Picture Mode LG
        - Settings LG
      - - touchpad
      - - Stop LG
        - Pause LG
        - Play LG
      - - Mute LG
        - VolumeMinus LG
        - VolumeUp LG
      - - slider2
  p3:
    type: custom:android-tv-card
    custom_actions:
      - type: slider
        name: slider2
        range:
          - 0
          - 0.2
        step: 0.01
        value_attribute: volume_level
        tap_action:
          action: perform-action
          perform_action: media_player.volume_set
          data:
            volume_level: "{{ value | float }}"
        entity_id: media_player.ht_zf9
        icon: mdi:volume-medium
      - type: touchpad
        name: touchpad
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55138018"
            command: Select
        up:
          tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "55138018"
              command: DirectionUp
          hold_action:
            action: repeat
          icon: mdi:arrow-up-bold
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            ommand: DirectionUp
          multi_tap_action:
            action: none
        down:
          tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "55138018"
              command: DirectionDown
          hold_action:
            action: repeat
          icon: mdi:arrow-down-bold
          multi_tap_action:
            action: none
        left:
          tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "55138018"
              command: DirectionLeft
          hold_action:
            action: repeat
          icon: mdi:arrow-left-bold
        right:
          tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "55138018"
              command: DirectionRight
          hold_action:
            action: repeat
          icon: mdi:arrow-right-bold
        icon: mdi:record
        double_tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55138018"
            command: Back
        hold_action:
          action: none
      - type: button
        name: button nada
        tap_action:
          action: none
      - type: button
        name: menu kodi
        icon: mdi:menu
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: C
        hold_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: S
      - type: button
        name: pc stop
        icon: mdi:stop
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target: null
          device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: X
      - type: button
        name: pc pause play
        icon: mdi:play-pause
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: Pause
      - type: button
        name: pc info
        icon: mdi:information-outline
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: Info
        hold_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: O
      - type: button
        name: harmony kodi
        icon: mdi:kodi
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: Win+4
      - type: button
        name: mute
        icon: mdi:volume-off
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: Mute
            device: "55138018"
      - type: button
        name: Navigate LG
        icon: phu:lg
        tap_action:
          action: navigate
          navigation_path: "#p2"
      - type: button
        name: Navigate Sony
        icon: si:sony
        styles: |-
          :host {
            --icon-color: rgb(255, 165, 0);
          }
        tap_action:
          action: navigate
          navigation_path: "#p3"
      - type: button
        name: Navigate Windows
        icon: mdi:microsoft-windows
        tap_action:
          action: navigate
          navigation_path: "#p4"
      - type: button
        name: Home Sony
        icon: mdi:home
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: Home
            device: "55138018"
      - type: button
        name: Power Sony
        icon: mdi:power-cycle
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: PowerToggle
            device: "55138018"
      - type: button
        name: Stop Sony
        icon: mdi:stop
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: Stop
            device: "55138018"
      - type: button
        name: Pause Sony
        icon: mdi:pause
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: Pause
            device: "55138018"
      - type: button
        name: Night Sony
        icon: mdi:weather-night
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: Night
            device: "55138018"
      - type: button
        name: VolumeDown Sony
        icon: mdi:volume-minus
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: VolumeDown
            device: "55138018"
      - type: button
        name: VolumeUp Sony
        icon: mdi:volume-plus
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: VolumeUp
            device: "55138018"
    platform: Kodi
    remote_id: remote.comedor
    keyboard_id: media_player.ht_zf9
    media_player_id: media_player.ht_zf9
    rows:
      - - Power Sony
      - - Navigate LG
        - Navigate Sony
        - Navigate Windows
      - - Home Sony
        - null
        - null
      - - touchpad
      - - Stop Sony
        - Pause Sony
        - Night Sony
      - - mute
        - VolumeDown Sony
        - VolumeUp Sony
      - - slider2
  p4:
    type: custom:android-tv-card
    custom_actions:
      - type: slider
        name: slider2
        range:
          - 0
          - 0.2
        step: 0.01
        value_attribute: volume_level
        tap_action:
          action: perform-action
          perform_action: media_player.volume_set
          data:
            volume_level: "{{ value | float }}"
            entity_id: media_player.ht_zf9
        icon: mdi:volume-medium
      - type: touchpad
        name: touchpad
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: OK
        up:
          tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "55023749"
              command: DirectionUp
          hold_action:
            action: repeat
          icon: mdi:arrow-up-bold
          multi_tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "55023749"
              command: ChannelUp
        down:
          tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "55023749"
              command: DirectionDown
          hold_action:
            action: repeat
          icon: mdi:arrow-down-bold
          multi_tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "55023749"
              command: ChannelDown
        left:
          tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "55023749"
              command: DirectionLeft
          hold_action:
            action: repeat
          icon: mdi:arrow-left-bold
        right:
          tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "55023749"
              command: DirectionRight
          hold_action:
            action: repeat
          icon: mdi:arrow-right-bold
        icon: mdi:record
        double_tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: Back
        hold_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: C
      - type: button
        name: home kodi
        icon: mdi:home
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: Exit
      - type: button
        name: menu kodi
        icon: mdi:menu
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: C
        hold_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: S
      - type: button
        name: Power
        icon: mdi:power-cycle
        tap_action:
          action: toggle
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
      - type: button
        name: pc stop
        icon: mdi:stop
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target: null
          device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: X
      - type: button
        name: pc pause play
        icon: mdi:play-pause
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: Pause
      - type: button
        name: pc info
        icon: mdi:information-outline
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: Info
        hold_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: O
      - type: button
        name: harmony kodi
        icon: mdi:kodi
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            device: "55023749"
            command: Win+3
      - type: button
        name: mute
        icon: mdi:volume-off
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: Mute
            device: "55138018"
      - type: button
        name: Navigate LG
        icon: phu:lg
        tap_action:
          action: navigate
          navigation_path: "#p2"
      - type: button
        name: Navigate Sony
        icon: si:sony
        tap_action:
          action: navigate
          navigation_path: "#p3"
      - type: button
        name: Navigate Windows
        icon: mdi:microsoft-windows
        styles: |-
          :host {
            --icon-color: rgb(0, 165, 222);
          }
        tap_action:
          action: navigate
          navigation_path: "#p4"
      - type: button
        name: HDMI3 LG
        icon: mdi:video-input-hdmi
        tap_action:
          action: perform-action
          perform_action: remote.send_command
          target:
            device_id: e3b24378972d017fe5c878df347a4a09
          data:
            num_repeats: 1
            delay_secs: 0.4
            hold_secs: 0
            command: InputHdmi3
            device: "74063740"
      - type: touchpad
        name: touchpad channel
        up:
          tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "55023749"
              command: ChannelUp
        tap_action:
          action: none
        double_tap_action:
          action: none
        hold_action:
          action: none
        down:
          tap_action:
            action: perform-action
            perform_action: remote.send_command
            target:
              device_id: e3b24378972d017fe5c878df347a4a09
            data:
              num_repeats: 1
              delay_secs: 0.4
              hold_secs: 0
              device: "55023749"
              command: ChannelDown
        left:
          tap_action:
            action: none
          hold_action:
            action: none
        right:
          tap_action:
            action: none
          hold_action:
            action: none
    platform: Kodi
    remote_id: remote.comedor
    keyboard_id: media_player.kodi_salon
    media_player_id: media_player.ht_zf9
    rows:
      - - Power
      - - Navigate LG
        - Navigate Sony
        - Navigate Windows
      - - home kodi
        - keyboard
        - menu kodi
      - - touchpad
      - - pc stop
        - pc pause play
        - pc info
      - - mute
        - HDMI3 LG
        - harmony kodi
      - - slider2
```

**Additional information:**

**Comment by Nerwyn** [comment]
It appears to be working on Android and Desktop, but not on iPhone. Damn you Apple. I'll have to fix this.

**Comment by Nerwyn** [comment]
@viseniv try the 4.3.1 alpha, it should fix it.

**Comment by houser42** [comment]
Hello.
Happy android-tv-card user here. Can't thank you enough for this card!
Came here to report the same issue but unable to select any alpha versions. Has that functionality moved?
Noted a new upload time on the stable version and downloaded that again and it seems to work now.
I guess you rolled the fix in there? Any way, seems to work now..

**Comment by Nerwyn** [comment]
Thanks for the confirmation @houser42! Fixed in [4.3.1](https://github.com/Nerwyn/android-tv-card/releases/tag/4.3.1).

**Comment by houser42** [comment]
Terribly sorry to go on, but the error appears to have come back in 4.3.1.
Going back to 4.2.1 still fixes it. Have reset cache and done the usual housework and pretty sure I am not doing something wrong.

**Comment by Nerwyn** [comment]
4.3.1 is the exact same build as 4.3.1 alpha. If the alpha build was working for you and 4.3.1 isn't, then it's a caching issue.

For reference the https://github.com/Nerwyn/android-tv-card/compare/4.3.0...4.3.1 patch version diff.

**Comment by houser42** [comment]
Ok.
Apologies, I then must have made a mistake when testing the alpha not thoroughly enough. My bad.
2.3.1 double click works on Apple TV but not on Kodi. 

Has something else changed  that means I need to revisit my settings or programming?
If not and unless I am mistaken, something else was introduced that affects only double click in Kodi on the iPhone app.
If that is possible. No worries, will stay on 2.2.1 for now.

**Comment by Nerwyn** [comment]
The tap/double/hold/etc detection is completely separate from the platforms and custom actions. If it's working for one platform and not another, it's either a caching or configuration error.

**Comment by houser42** [comment]
ok. I will try again but have switched between the versions several times with the same result and clearing case nd restart on iPhone. I assume not a config error, as it works 100% on 4.2.1.
Ah well.
If someone else with the iPhone app has or does not have this issue and can confirm either here I would appreciate it.

**Comment by houser42** [comment]
This issue persists in 4.3.3. Pretty sure it is not a cache issue on my part. Ah well.
Best wishes for 2025!

**Comment by houser42** [comment]
This issue still persists here in 4.3.4.  No double-tap for back command in Kode that is.
No biggie as yet, as I am currently absolutely fine on 4.2.1 but I guess at some point it will be a good idea to be up to date.
If you could have a look at some point when there is time at my code below to see if something is wrong in there that could trigger this issue. This code is flawless in 4.2.1 but kills the double-tap in Kodi. Many thanks.

```
type: custom:android-tv-card
keyboard_id: media_player.kodi
rows:
  - - touchpad
custom_actions:
  - type: button
    name: up
    tap_action:
      action: perform-action
      perform_action: kodi.call_method
      data:
        method: Input.Up
      target:
        entity_id: media_player.kodi
    hold_action:
      action: repeat
    icon: mdi:chevron-up
    multi_tap_action:
      action: perform-action
      data:
        method: Input.ExecuteAction
        action: pageup
      perform_action: kodi.call_method
      target:
        entity_id: media_player.kodi
  - type: button
    name: down
    tap_action:
      action: perform-action
      perform_action: kodi.call_method
      data:
        method: Input.Down
      target:
        entity_id: media_player.kodi
    hold_action:
      action: repeat
    icon: mdi:chevron-down
    multi_tap_action:
      action: perform-action
      data:
        method: Input.ExecuteAction
        action: pagedown
      perform_action: kodi.call_method
      target:
        entity_id: media_player.kodi
  - type: button
    name: left
    tap_action:
      action: perform-action
      perform_action: kodi.call_method
      data:
        method: Input.Left
      target:
        entity_id: media_player.kodi
    hold_action:
      action: repeat
    icon: mdi:chevron-left
  - type: button
    name: right
    tap_action:
      action: perform-action
      perform_action: kodi.call_method
      data:
        method: Input.Right
      target:
        entity_id: media_player.kodi
    hold_action:
      action: repeat
    icon: mdi:chevron-right
  - type: button
    name: center
    tap_action:
      action: perform-action
      perform_action: kodi.call_method
      data:
        method: Input.Select
      target:
        entity_id: media_player.kodi
    icon: mdi:checkbox-blank-circle
    double_tap_action:
      action: perform-action
      perform_action: kodi.call_method
      data:
        method: Input.Back
      target:
        entity_id: media_player.kodi
    hold_action:
      action: perform-action
      perform_action: kodi.call_method
      data:
        method: Input.ContextMenu
      target:
        entity_id: media_player.kodi
    multi_tap_action:
      action: perform-action
      data:
        method: Input.ContextMenu
      perform_action: kodi.call_method
      target:
        entity_id: media_player.kodi
    multi_hold_action:
      action: perform-action
      data:
        method: Input.ContextMenu
      perform_action: kodi.call_method
      target:
        entity_id: media_player.kodi
    multi_double_tap_action:
      action: perform-action
      data:
        method: Input.ContextMenu
      perform_action: kodi.call_method
      target:
        entity_id: media_player.kodi
  - type: touchpad
    name: touchpad
    tap_action:
      action: perform-action
      perform_action: kodi.call_method
      data:
        method: Input.Select
      target:
        entity_id: media_player.kodi
    up:
      tap_action:
        action: perform-action
        perform_action: kodi.call_method
        data:
          method: Input.Up
        target:
          entity_id: media_player.kodi
      hold_action:
        action: repeat
      multi_tap_action:
        action: perform-action
        data:
          method: Input.ExecuteAction
          action: pageup
        perform_action: kodi.call_method
        target:
          entity_id: media_player.kodi
      name: up
      type: button
    down:
      tap_action:
        action: perform-action
        perform_action: kodi.call_method
        data:
          method: Input.Down
        target:
          entity_id: media_player.kodi
      hold_action:
        action: repeat
      multi_tap_action:
        action: perform-action
        data:
          method: Input.ExecuteAction
          action: pagedown
        perform_action: kodi.call_method
        target:
          entity_id: media_player.kodi
      name: down
      type: button
    left:
      tap_action:
        action: perform-action
        perform_action: kodi.call_method
        data:
          method: Input.Left
        target:
          entity_id: media_player.kodi
      hold_action:
        action: repeat
      name: left
      type: button
    right:
      tap_action:
        action: perform-action
        perform_action: kodi.call_method
        data:
          method: Input.Right
        target:
          entity_id: media_player.kodi
      hold_action:
        action: repeat
      name: right
      type: button
    styles: |-
      toucharea {
        height: 295px;
        background-image: url("/local/jtm-bg/Kodi75b.png");
        background-size: xxx;
        background-repeat: no-repeat;
        background-position: center;
        opacity: 0.4;
        background-color: rgba(0, 0, 0, 0.2);
      }
    haptics: false
    hold_action:
      action: perform-action
      perform_action: kodi.call_method
      data:
        method: Input.ContextMenu
      target:
        entity_id: media_player.kodi
    double_tap_action:
      action: perform-action
      perform_action: kodi.call_method
      data:
        method: Input.Back
      target:
        entity_id: media_player.kodi
    multi_tap_action:
      action: perform-action
      data:
        method: Input.ContextMenu
      perform_action: kodi.call_method
      target:
        entity_id: media_player.kodi
    multi_hold_action:
      action: perform-action
      data:
        method: Input.ContextMenu
      perform_action: kodi.call_method
      target:
        entity_id: media_player.kodi
    multi_double_tap_action:
      action: perform-action
      data:
        method: Input.ContextMenu
      perform_action: kodi.call_method
      target:
        entity_id: media_player.kodi
platform: Kodi
card_mod:
  style: |
    :host {
      --ha-card-background: #00000000;
```
