### ISSUE TITLE
multi digits key

### ISSUE THREAD

**Issue by MiroG225** [Nerwyn/android-tv-card#172]
I have tens of these actions to switch a tv channels:

` - type: button`
`   name: nova`
`   autofill_entity_id: true`
`   haptics: true`
`   tap_action:`
`     action: key`
`     key: "5"`
`   label: Nova TV`

        
...but cannot find a way to switch to chnnel number 10 (and higher), where need to be pressed more than one digit.

and one more question:
How to switch to 'TV' input by Custom action? (I know there is 'TV' default key, but I need to customize it)

**Comment by Nerwyn** [comment]
> but cannot find a way to switch to chnnel number 10 

That action is shorthand for this Home Assistant action:

```yaml
action: perform-action
perform_action: remote.send_command
data:
  command: "5"
target:
  entity_id: media_player.android_tv
```

According to the underlying Python package used for the Android TV remote integration (assuming you're using the Android TV platform), [only 0-9 are valid keys](https://github.com/tronikos/androidtvremote2/blob/main/TvKeys.txt#L37-L46). You could try making a script to send two numbers back to back, or just press the numbers in quick succession yourself but there's no guarantee that'll work.

You could try using the `media_player.play_media` action as described in [the Android TV Remote integration documentation](https://www.home-assistant.io/integrations/androidtv_remote/#switch-channels) instead. That explicitly calls out changing channels as a feature.

```yaml
# Change channel to number 15:
action: perform-action
perform_action: media_player.play_media
data:
  media_content_type: channel
  media_content_id: 15
target:
  entity_id: media_player.android_tv
```

> How to switch to 'TV' input by Custom action? 

That will vary by your TV. If one of the keys in the list I linked above doesn't work, then it probably isn't possible via the Android TV remote integration. You may have to see if you're TV has a separate integration that can be used, or use a smart IR remote.
