### ISSUE TITLE
toucharea background image using template

### ISSUE THREAD

**Issue by Vansmak** [Nerwyn/android-tv-card#173]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser
- [ ] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**
No image shows when I use temple like I. The example  background-image: url("http://homeassistant.local:8123{{ state_attr(config.entity, 'entity_picture') }}");
        Or in my instance trying to use 
background-image: url("{{ states.input_text.touchpad_bg_url.state }}");
No image but when I use the direct image that matches the sensor it works 
http://192.168.254.64:8123/local/upcoming-media-card-images/plex/Recently_Added_TV/f50509.jpg

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Remote Config**

```yaml

```

**Additional information:**

**Comment by Nerwyn** [comment]
This is working fine for me:

```css
toucharea {
  background-image: url("http://homeassistant.local:8123{{ state_attr(config.entity, 'entity_picture') }}");
  background-repeat: no-repeat;
  background-size: contain;
  background-position: center;
}
```

Can you access your Home Assistant instance with the url http://homeassistant.local:8123? What if you change that portion to the IP address and port like you list above? Or remove it altogether?

You can also see what is actually rendered in the CSS styles using the browser dev tools (right click then Inspect or CTRL + SHIFT + I, then the arrow and square button in the top left or CTRL + SHIFT + C to select the touchpad `toucharea` and see the styles window.).

![Screenshot 2025-01-12 183248](https://github.com/user-attachments/assets/e782e009-98e0-4a51-a334-8f18edd9507d)
