### ISSUE TITLE
Refactor Interaction Detection to use Pointer Events

### ISSUE THREAD

**Issue by Nerwyn** [Nerwyn/android-tv-card#174]
**Is your feature request related to a problem? Please describe.**
Touch Event behavior is inconsistent across platforms, especially iOS webview leading to bugs.

**Describe the solution you'd like**
Pointer Events are a newer standard and behave much more consistently across platforms while also supporting multi-touch. They should replace touch events in the existing interaction detection logic, while still falling back to mouse events for desktop and ancient devices.

**Describe alternatives you've considered**
Leave it as is but I want to make things work for @houser42

**Additional context**
[JS Fiddle](https://jsfiddle.net/nerwyn/k6yt73mf/latest) for testing out pointer event logic and figuring out how to best implement it as a replacement for touch events.

**Comment by Nerwyn** [comment]
@houser42 can you try the latest 4.3.6 alpha? I think I got everything working as expected with pointer events. Tested it on iPhone as well.

**Comment by houser42** [comment]
Yes, the double-tap appears to be working again on iPhone. Will test it some more but it seems fine. Great!

However, this refactoring appears to have broken placement of the background image on touch area somewhat.
If the below code is correct still, which worked up to 4.2.1.
The size setting does no longer works on Linux and Mac browsers and bg image becomes invisible
The placement of bg image is also inconsistent on iPhone. Hope this helps.

```
    styles: |-
      toucharea {
        height: 325px;
        background-image: url("/local/jtm-bg/Apple_TV_logo_75.png");
        background-size: 64px;
        background-repeat: no-repeat;
        background-position: center;
        opacity: 0.4;
        background-color: rgba(0, 0, 0, 0.2);
      }
```

**Comment by Nerwyn** [comment]
Can you try changing to the default or a different theme? [I did fix how the touchpad background is set](https://github.com/Nerwyn/android-tv-card/commit/62ce265302491725d9233a402f11f9c1d44bafe3#diff-6a13837c31fe6ae8b1743a8d1c5004cbd4857e57e354ec1dea269868ac4c0765L368-R369) to get around a bug with Home Assistant themes where it would use a default theme color instead of a user set theme one in the last patch version.

I'm not sure why `background-size` would stop working though. That's a purely CSS field that's being applied to the card styles as is.

**Comment by houser42** [comment]
Yes, you are correct as usual;) Problem goes away if I use the HA standard theme.
I will use that of now. All working..

**Comment by Nerwyn** [comment]
Try setting your background image in the same line

```css
toucharea {
  background: url("https://www.shareicon.net/data/2016/02/07/281232_apple_512x512.png"), rgba(0, 0, 0, 0.2);
  background-size: 50%;
  background-repeat: no-repeat;
  background-position: center;
  opacity: 0.4;
}
```

or alternatively unset background before setting the image and color (less likely to work but worth a shot).

```css
toucharea {
  background: unset;
  background-image: url("https://www.shareicon.net/data/2016/02/07/281232_apple_512x512.png");
  background-color: rgba(0, 0, 0, 0.2);
  background-size: 50%;
  background-repeat: no-repeat;
  background-position: center;
  opacity: 0.4;
}
```
