### ISSUE TITLE
Is long press /hold possible for Apple TV options?

### ISSUE THREAD

**Issue by houser42** [Nerwyn/android-tv-card#178]
The Apple TV has a long press/hold feature that brings up a context menu in standard ways.
It would be great if it could be done on this fab card. AFAIK it can not be done presently ?

I would like press and hold to behave like the Apple Remote and remote apps work.

I am now using a button in HA to open the standard Apple Remote for this.

Grateful for a hint if this is or will be possible at all at some point.

**Comment by Nerwyn** [comment]
Did you not try remapping the `center` button hold action to something like `menu`? [Apple remote commands list ](https://www.home-assistant.io/integrations/apple_tv#remote) and [README section on interactions](https://github.com/Nerwyn/android-tv-card?tab=readme-ov-file#interactions) for reference.

**Comment by houser42** [comment]
As I understand it the command needed is either probably `select_hold` which is not in the HA command list
inorder to bring up the context menu rather than `menu` which just goes back one level in navigation.
This is probably not working natively in HA as yet, but you have worked your magic before ;) and perhaps
some code can be used as discussed in the example here: https://github.com/home-assistant/core/pull/105689
If you come across something maybe just keep it in the backlog? It is th only command which is not working via this card as yet.
Many thanks.

**Comment by Nerwyn** [comment]
It sounds like this is an issue with the Apple TV integration then. According to the thread you should try adding `hold_secs: 1` to the `remote.send_command` data. Try firing this command with the dev tool or remote card:

```yaml
action: perform-action
perform_action: remote.send_command
target:
  entity_id: remote.apple_tv
data:
  hold_secs: 1
  command: select
```

As of now the remote card automatically adds `hold_secs: 0.5` to key actions when held if no hold action is defined. If `hold_secs: 1` works for Apple TV I can test to see if it also works fine for Android TV and change it in a patch version.

**Comment by Nerwyn** [comment]
That's the frontend card syntax, the dev tools syntax is slightly different:

```yaml
action: remote.send_command
target:
  entity_id: remote.lounge_google_tv
data:
  hold_secs: 1
  command: select
```

I looked at [the Apple TV remote code](https://github.com/home-assistant/core/blob/cf8409dcd2d7f070f91cecfc8b4ee265091d4860/homeassistant/components/apple_tv/remote.py#L91-L92) and it should send the a hold command to the TV if `hold_secs` is greater or equal to 1.

If you're trying to remap the touchpad center action, then you need to create a touchpad custom action and remap it there. It would look something like this:

```yaml
type: custom:android-tv-card
rows:
  - - touchpad
custom_actions:
  - type: touchpad
    name: touchpad
    tap_action:
      action: key
      key: select
    up:
      tap_action:
        action: key
        key: up
      hold_action:
        action: repeat
    down:
      tap_action:
        action: key
        key: down
      hold_action:
        action: repeat
    left:
      tap_action:
        action: key
        key: left
      hold_action:
        action: repeat
    right:
      tap_action:
        action: key
        key: right
      hold_action:
        action: repeat
    hold_action:
      action: perform-action
      perform_action: remote.send_command
      target: {}
      data:
        command: select
        hold_secs: 1
platform: Apple TV
remote_id: remote.apple_tv
```
