### ISSUE TITLE
Touchpad double tap not registering 90% of attempts

### ISSUE THREAD

**Issue by alatum** [Nerwyn/android-tv-card#183]
**Checklist:**

- [Y] I updated to the latest version available
- [Y] I cleared the cache of my browser
- [Y] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**
Latest V4.3.10

**Last working release (if known):**
Two releases ago

**Browser and Operating System:**
Android Latest App 2025.1.2-full
Firefox debian 12
Edge windows 11

**Description of problem:**

Touchpad double tap has suddenly stopped working as intended,  instead it registers as a single tap or an up or down swipe. With the occasional double tap registered.

Beforehand,  a double tap would execute the correct remote command, every time. 

I've attempted to adjust the tap window ms to allow more time for a double tap (just incase my reflexes have slowed) but same issue. Worked fine upto 2 releases ago. 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Remote Config**

```yaml

```

**Additional information:**
Tried to remove integration and recode the remore, issue remains. No other changes or updates to consider a contributing factor.

**Comment by Nerwyn** [comment]
I'm not sure why it started, but I'm also able to reproduce this on Android intermittently. It seems to be fine on desktop browsers though. I think I can greatly reduce the sensitivity of touchpad swipes which should fix this without affecting other users. Can you try the 4.3.11 alpha and see if that fixes it for you?

For reference here's my debugger remote layout which helps give a clearer picture of which action is firing. I normally don't use all of these interaction types so this remote layout helps me debug interactions and haptics.

```yaml
type: custom:android-tv-card
autofill_entity_id: true
rows:
  - - success
    - warning
    - failure
  - - light
    - medium
    - heavy
    - selection
  - - power
    - momentary_pad
    - home
  - - touchpad
custom_actions:
  - type: button
    name: power
    tap_action:
      action: eval
      eval: |-
        const actionType = 'tap_action'
        console.log(actionType) const event =
        new Event('hass-notification', { bubbles: true, composed: true })
        event.detail = { message: actionType } this.dispatchEvent(event)
    icon: mdi:power
    hold_action:
      action: eval
      eval: >-
        const actionType = 'hold_action'

        console.log(actionType)

        const event = new Event('hass-notification', { bubbles: true, composed:
        true })

        event.detail = { message: actionType }

        this.dispatchEvent(event)
    double_tap_action:
      action: eval
      eval: >-
        const actionType = 'double_tap_action'

        console.log(actionType)

        const event = new Event('hass-notification', { bubbles: true, composed:
        true })

        event.detail = { message: actionType }

        this.dispatchEvent(event)
  - type: touchpad
    name: touchpad
    tap_action:
      action: eval
      eval: >-
        const actionType = 'tap_action'

        console.log(actionType)

        const event = new Event('hass-notification', { bubbles: true, composed:
        true })

        event.detail = { message: actionType }

        this.dispatchEvent(event)
    up:
      tap_action:
        action: eval
        eval: >-
          const actionType = 'up_swipe_action'

          console.log(actionType)

          const event = new Event('hass-notification', { bubbles: true,
          composed: true })

          event.detail = { message: actionType }

          this.dispatchEvent(event)
      hold_action:
        action: repeat
      styles: ""
      multi_tap_action:
        action: eval
        eval: >-
          const actionType = 'up_multi_swipe_action'

          console.log(actionType)

          const event = new Event('hass-notification', { bubbles: true,
          composed: true })

          event.detail = { message: actionType }

          this.dispatchEvent(event)
      multi_hold_action:
        action: eval
        eval: >-
          const actionType = 'up_multi_hold_action'

          console.log(actionType)

          const event = new Event('hass-notification', { bubbles: true,
          composed: true })

          event.detail = { message: actionType }

          this.dispatchEvent(event)
    down:
      tap_action:
        action: eval
        eval: >-
          const actionType = 'down_swipe_action'

          console.log(actionType)

          const event = new Event('hass-notification', { bubbles: true,
          composed: true })

          event.detail = { message: actionType }

          this.dispatchEvent(event)
      hold_action:
        action: eval
        eval: >-
          const actionType = 'down_hold_action'

          console.log(actionType)

          const event = new Event('hass-notification', { bubbles: true,
          composed: true })

          event.detail = { message: actionType }

          this.dispatchEvent(event)
      styles: ""
      multi_tap_action:
        action: eval
        eval: >-
          const actionType = 'down_multi_swipe_action'

          console.log(actionType)

          const event = new Event('hass-notification', { bubbles: true,
          composed: true })

          event.detail = { message: actionType }

          this.dispatchEvent(event)
      multi_hold_action:
        action: repeat
    left:
      tap_action:
        action: eval
        eval: >-
          const actionType = 'left_swipe_action'

          console.log(actionType)

          const event = new Event('hass-notification', { bubbles: true,
          composed: true })

          event.detail = { message: actionType }

          this.dispatchEvent(event)
      hold_action:
        action: eval
        eval: >-
          const actionType = 'left_hold_action'

          console.log(actionType)

          const event = new Event('hass-notification', { bubbles: true,
          composed: true })

          event.detail = { message: actionType }

          this.dispatchEvent(event)
      styles: ""
      multi_tap_action:
        action: eval
        eval: >-
          const actionType = 'left_multi_swipe_action'

          console.log(actionType)

          const event = new Event('hass-notification', { bubbles: true,
          composed: true })

          event.detail = { message: actionType }

          this.dispatchEvent(event)
      multi_hold_action:
        action: repeat
    right:
      tap_action:
        action: eval
        eval: >-
          const actionType = 'right_swipe_action'

          console.log(actionType)

          const event = new Event('hass-notification', { bubbles: true,
          composed: true })

          event.detail = { message: actionType }

          this.dispatchEvent(event)
      hold_action:
        action: repeat
      styles: ""
      multi_tap_action:
        action: eval
        eval: >-
          const actionType = 'right_multi_swipe_action'

          console.log(actionType)

          const event = new Event('hass-notification', { bubbles: true,
          composed: true })

          event.detail = { message: actionType }

          this.dispatchEvent(event)
      multi_hold_action:
        action: eval
        eval: >-
          const actionType = 'right_multi_hold_action'

          console.log(actionType)

          const event = new Event('hass-notification', { bubbles: true,
          composed: true })

          event.detail = { message: actionType }

          this.dispatchEvent(event)
    styles: |-
      .icon {
        --size: 250px;
      }
      .toucharea-row {
        justify-content: center;
      }
      xtoucharea {
        xbackground: url("https://www.shareicon.net/data/2016/02/07/281232_apple_512x512.png"), rgba(0, 0, 0, 0.2);
        background: unset;
        background-image: url("https://www.shareicon.net/data/2016/02/07/281232_apple_512x512.png");
        background-color: rgba(0, 0, 0, 0.2);
        background-size: 50%;
        background-repeat: no-repeat;
        background-position: center;
        opacity: 0.4;
      }
    double_tap_action:
      action: eval
      eval: >-
        const actionType = 'double_tap_action'

        console.log(actionType)

        const event = new Event('hass-notification', { bubbles: true, composed:
        true })

        event.detail = { message: actionType }

        this.dispatchEvent(event)
    icon: mdi:apple
    hold_action:
      action: eval
      eval: >-
        const actionType = 'hold_action'

        console.log(actionType)

        const event = new Event('hass-notification', { bubbles: true, composed:
        true })

        event.detail = { message: actionType }

        this.dispatchEvent(event)
      hold_time: 500
    multi_tap_action:
      action: eval
      eval: >-
        const actionType = 'multi_tap_action'

        console.log(actionType)

        const event = new Event('hass-notification', { bubbles: true, composed:
        true })

        event.detail = { message: actionType }

        this.dispatchEvent(event)
    multi_double_tap_action:
      action: eval
      eval: >-
        const actionType = 'multi_double_tap_action'

        console.log(actionType)

        const event = new Event('hass-notification', { bubbles: true, composed:
        true })

        event.detail = { message: actionType }

        this.dispatchEvent(event)
    multi_hold_action:
      action: eval
      eval: >-
        const actionType = 'multi_hold_action'

        console.log(actionType)

        const event = new Event('hass-notification', { bubbles: true, composed:
        true })

        event.detail = { message: actionType }

        this.dispatchEvent(event)
      hold_time: 500
  - type: button
    name: home
    tap_action:
      action: key
      key: home
    icon: mdi:home
    momentary_start_action:
      action: eval
      eval: >-
        const actionType = 'momentary_start_action'

        console.log(actionType)

        const event = new Event('hass-notification', { bubbles: true, composed:
        true })

        event.detail = { message: actionType }

        this.dispatchEvent(event)
    momentary_end_action:
      action: eval
      eval: >-
        const actionType = 'momentary_end_action'

        console.log(actionType)

        const event = new Event('hass-notification', { bubbles: true, composed:
        true })

        event.detail = { message: actionType }

        this.dispatchEvent(event)
  - type: touchpad
    name: momentary_pad
    momentary_start_action:
      action: eval
      eval: >-
        const actionType = 'momentary_start_action'

        console.log(actionType)

        const event = new Event('hass-notification', { bubbles: true, composed:
        true })

        event.detail = { message: actionType }

        this.dispatchEvent(event)
    momentary_end_action:
      action: eval
      eval: >-
        const actionType = 'momentary_end_action'

        console.log(actionType)

        const event = new Event('hass-notification', { bubbles: true, composed:
        true })

        event.detail = { message: actionType }

        this.dispatchEvent(event)
    up:
      tap_action:
        action: eval
        eval: |-
          console.log('up_swipe_action')
          navigator.userAgent.includes('iPhone') && alert('up_swipe_action')
      hold_action:
        action: repeat
      styles: ""
      multi_tap_action:
        action: eval
        eval: >-
          console.log('up_multi_swipe_action')

          navigator.userAgent.includes('iPhone') &&
          alert('up_multi_swipe_action')
      multi_hold_action:
        action: eval
        eval: >-
          console.log('up_multi_hold_action')

          navigator.userAgent.includes('iPhone') &&
          alert('up_multi_hold_action')
    down:
      tap_action:
        action: eval
        eval: |-
          console.log('down_swipe_action')
          navigator.userAgent.includes('iPhone') && alert('down_swipe_action')
      hold_action:
        action: eval
        eval: |-
          console.log('down_hold_action')
          navigator.userAgent.includes('iPhone') && alert('down_hold_action')
      styles: ""
      multi_tap_action:
        action: eval
        eval: >-
          console.log('down_multi_swipe_action')

          navigator.userAgent.includes('iPhone') &&
          alert('down_multi_swipe_action')
      multi_hold_action:
        action: repeat
    left:
      tap_action:
        action: eval
        eval: |-
          console.log('left_swipe_action')
          navigator.userAgent.includes('iPhone') && alert('left_swipe_action')
      hold_action:
        action: eval
        eval: |-
          console.log('left_hold_action')
          navigator.userAgent.includes('iPhone') && alert('left_hold_action')
      styles: ""
      multi_tap_action:
        action: eval
        eval: >-
          console.log('left_multi_swipe_action')

          navigator.userAgent.includes('iPhone') &&
          alert('left_multi_swipe_action')
      multi_hold_action:
        action: repeat
    right:
      tap_action:
        action: eval
        eval: |-
          console.log('right_swipe_action')
          navigator.userAgent.includes('iPhone') && alert('right_swipe_action')
      hold_action:
        action: repeat
      styles: ""
      multi_tap_action:
        action: eval
        eval: >-
          console.log('right_multi_swipe_action')

          navigator.userAgent.includes('iPhone') &&
          alert('right_multi_swipe_action')
      multi_hold_action:
        action: eval
        eval: >-
          console.log('right_multi_hold_action')

          navigator.userAgent.includes('iPhone') &&
          alert('right_multi_hold_action')
    styles: |-
      toucharea {
        height: 48px;
        width: 96px;
        flex-grow: 0;
      }
  - type: button
    name: success
    tap_action:
      action: eval
      eval: |-
        const event = new Event('haptic', {
            bubbles: true,
            composed: true,
        });
        event.detail = "success";
        this.dispatchEvent(event);
    icon: mdi:check
    hold_action:
      action: repeat
    styles: ""
    haptics: false
  - type: button
    name: warning
    tap_action:
      action: eval
      eval: |-
        const event = new Event('haptic', {
            bubbles: true,
            composed: true,
        });
        event.detail = "warning";
        this.dispatchEvent(event);
    icon: mdi:alert
    hold_action:
      action: repeat
    haptics: false
  - type: button
    name: failure
    tap_action:
      action: eval
      eval: |-
        const event = new Event('haptic', {
            bubbles: true,
            composed: true,
        });
        event.detail = "failure";
        this.dispatchEvent(event);
    icon: mdi:alert-decagram
    hold_action:
      action: repeat
    haptics: false
  - type: button
    name: light
    tap_action:
      action: eval
      eval: |-
        const event = new Event('haptic', {
            bubbles: true,
            composed: true,
        });
        event.detail = "light";
        this.dispatchEvent(event);
    icon: mdi:circle-small
    hold_action:
      action: repeat
    haptics: false
  - type: button
    name: medium
    tap_action:
      action: eval
      eval: |-
        const event = new Event('haptic', {
            bubbles: true,
            composed: true,
        });
        event.detail = "medium";
        this.dispatchEvent(event);
    icon: mdi:circle-medium
    hold_action:
      action: repeat
    haptics: false
  - type: button
    name: heavy
    tap_action:
      action: eval
      eval: |-
        const event = new Event('haptic', {
            bubbles: true,
            composed: true,
        });
        event.detail = "heavy";
        this.dispatchEvent(event);
    icon: mdi:circle
    hold_action:
      action: repeat
    haptics: false
  - type: button
    name: selection
    tap_action:
      action: eval
      eval: |-
        const event = new Event('haptic', {
            bubbles: true,
            composed: true,
        });
        event.detail = "selection";
        this.dispatchEvent(event);
    icon: mdi:selection
    hold_action:
      action: repeat
    haptics: false
title: Debugger
```
