### ISSUE TITLE
androidtv/adb_command

### ISSUE THREAD

**Issue by jboesh** [Nerwyn/android-tv-card#19]
Hi, I am trying to get the Search working that you describe here (https://github.com/Nerwyn/android-tv-card#google-assistant-search). When I just add "search" in my lovelace card I get this error:

`Cannot call service androidtv/adb_command. must contain at least one of entity_id, device_id, area_id.
`
so I have to work with custom keys I assume?

so I if I add the following:

```
    custom_keys:
      search:
        service: androidtv.adb_command
        service_data:
          entity_id: media_player.samsung_au7100_70_tv
```

I get this error:

`Cannot call service androidtv/adb_command. required key not provided @ data['command']`

so I need to add a command I guess, but when I put something like this it doesn't work. the text box doesnt appear:

```
    custom_keys:
      search:
        service: androidtv.adb_command
        service_data:
          entity_id: media_player.samsung_au7100_70_tv
          command: HOME
```

but that's strange because what I enter in the text box should be sent as a "command", right?
-> 
![image](https://github.com/Nerwyn/android-tv-card/assets/71582854/0e0dc104-7d81-4978-a6c9-22b72e4a3452)

or am I missing something here?

I have added Android Debug Bridge successfully in HA dus ABD is correctly configured on my TV.

**Comment by Nerwyn** [comment]
Please post your full config. You should have the `keyboard_id` (formerly `adb_id` which also still works) option filled out with your Android TV ADB media player entity ID.

**Comment by jboesh** [comment]
my full config:
I've set "keyboard_id" and "search" but the "search" is asking for the "command" like I described above.

```
type: vertical-stack
cards:
  - type: custom:mini-media-player
    entity: media_player.samsung_au7100_70_tv
    volume_stateless: false
  - type: media-control
    entity: media_player.chromecast_2
  - type: custom:android-tv-card
    remote_id: remote.chromecastwoonkamer
    media_player_id: media_player.samsung_au7100_70_tv
    keyboard_id: media_player.samsung_au7100_70_tv
    title: TVWoonkamer
    rows:
      - - back
        - power
        - home
        - search
      - - volume_down
        - volume_mute
        - volume_up
      - - navigation_buttons
      - - netflix
        - youtube
        - disney
        - spotify
      - - previous
        - rewind
        - play_pause
        - fast_forward
        - next
    custom_keys:
      volume_down:
        service: media_player.volume_down
        service_data:
          entity_id: media_player.samsung_au7100_70_tv
      volume_mute:
        service: media_player.volume_mute
        service_data:
          entity_id: media_player.samsung_au7100_70_tv
          is_volume_muted: true
      volume_up:
        service: media_player.volume_up
        service_data:
          entity_id: media_player.samsung_au7100_70_tv
      search:
        service: androidtv.adb_command
        service_data:
          entity_id: media_player.samsung_au7100_70_tv
          command: ???
```
