### ISSUE TITLE
card mod code affected by upgrade from 2.1.3 to 2.2.0 ?

### ISSUE THREAD

**Issue by houser42** [Nerwyn/android-tv-card#22]
Hello,

Just a note that the code you gave us for card mod to do transparency stopped working with 2.2.0.
Gray screen for the touch area again. Going back to 2.1.3 fixed it.
Below code is what I am currently using, perhaps it needs to change with 2.2.0?
Many thanks.

```
card_mod:
  style: |
    :host {
      --ha-card-background: #00000000;
    }
    toucharea {
      background: #00000000;
      background-image: url("/hacsfiles/themes/jtm-bg/Apple_TV_logo_75.png");
      opacity: 0.9;
      background-repeat: no-repeat
    }
```

**Comment by Nerwyn** [comment]
It's working for me, but your yaml is missing a value after the decimal under opacity.

**Comment by houser42** [comment]
Thanks. The opacity is just for the overlaid image so that changed only that in 2.1.3.
I can not get this to work with my card mod code.
Will try some more when there is time. But I can not affect anything with card mod here with 2.2. Odd.
Maybe I have som other conflict. Will trouble shoot..

**Comment by Nerwyn** [comment]
The opacity should have always been for the entire touchpad, including the image.

While I did modify the touchpad style logic, I'm not sure why the example doesn't work anymore as is. I got it to work again by add ` !important` to the end of each property except `opacity` which still seems to work. I'll have to update the README examples.

```css
toucharea {
  background-image: url("https://upload.wikimedia.org/wikipedia/commons/a/ab/Apple-logo.png") !important;
  background-size: contain !important;
  background-repeat: no-repeat !important;
  background-position: center !important;
  opacity: 0.1;
    }
```

**Comment by houser42** [comment]
Thanks. This is not working here for some reason.  Might be typos or formatting. Will troubleshoot more carefully over the weekend.
Many thanks.

**Comment by houser42** [comment]
Spent some more time and got it to work again with the latest version 2.1.1. Great thanks!

Question:
Is it possible to set opacity for touch area and background image separately?
I want 0 for bg and some other number for the BG image.

I am pretty sure I was able to do this with 2.1.3 but that could have been a happy accident?

**Comment by Nerwyn** [comment]
There isn't a good way to set the opacity of the background image separately. You could set the background color using an rgba function or hex color to control the background color opacity separately from the image, and then set the overall opacity on top of that.

```css
toucharea {
  background-image: url("https://upload.wikimedia.org/wikipedia/commons/a/ab/Apple-logo.png") !important;
  background-size: contain !important;
  background-repeat: no-repeat !important;
  background-position: center !important;
  background-color: rgba(172, 179, 182, 0.2) !important;
}
```
