### ISSUE TITLE
Default Layout

### ISSUE THREAD

**Issue by Nerwyn** [Nerwyn/android-tv-card#226]
**Is your feature request related to a problem? Please describe.**
New users can be confused by the lack of buttons present in the card when they first set it up. I should include some default layouts that they can choose from.
- 3-10 default layouts included with the card.
- On card creation layout defaults to the first default layout.
- All default layouts have to use keys that are common to all platforms.
  - I may need to add some buttons to some layouts.

**Describe the solution you'd like**
A list of default layouts and a dropdown to select them in the layout tab.

**Describe alternatives you've considered**
Users could just enter their own layout.

**Additional context**
NA

**Comment by Nerwyn** [comment]
Dumbing this down to just providing a single default remote layout on card creation. Users should be able to copy other examples from the README.

**Comment by felipecrs** [comment]
Something else I'd like to mention is that I think these styles make a lot more sense out of the box:

```yaml
styles: |-
  .row {
    margin-top: 4px;
    margin-bottom: 4px;
  }
  .empty-button {
    padding: 8px;
  }
  remote-button {
    border-radius: 40%;
    background: rgb(17, 17, 17);
    padding: 8px;
  }
```

## Before and after

<img width="400" height="453" alt="Image" src="https://github.com/user-attachments/assets/7b68ec7d-7c9d-4982-923e-c107dab58519" />

<img width="380" height="1006" alt="Image" src="https://github.com/user-attachments/assets/6680c07a-f9bb-4c0c-b699-106379e2eea8" />

But that is for sure opinionated. I just wanted to share this with you.
