### ISSUE TITLE
Card mod stopped working for v3.0.0-dev.032

### ISSUE THREAD

**Issue by tikel1** [Nerwyn/android-tv-card#24]
**Checklist:**

- [v] I updated to the latest version available
- [v] I cleared the cache of my browser

**Release with the issue:**
v3.0.0-dev.032
**Last working release (if known):**
v2.2.1
**Browser and Operating System:**
Chrome Win11

**Description of problem:**
After upgrading to v3.0.0-dev.032 (I'm not registered for beta) several features of card mod stopped working such as **ha-icon-button** and **ha-icon**

![image](https://github.com/Nerwyn/android-tv-card/assets/121404448/4504d794-2542-464e-8a19-a48a79e6a152)
![image](https://github.com/Nerwyn/android-tv-card/assets/121404448/c046a264-9c01-43ac-97f1-a33b87f3c009)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Remote Config**

```yaml

```

**Additional information:**

**Comment by Nerwyn** [comment]
1. Please do not use the dev builds, they are likely to be very broken.
2. Because of the significant rewrites in version 3, card mod will not work well with this card due to shadow roots. I plan to compensate for this with more advanced style options.

**Comment by tikel1** [comment]
Thanks for your reply, for some reason it offers the dev version as production:
![image](https://github.com/Nerwyn/android-tv-card/assets/121404448/4e53a4cf-6a58-4c5d-9d67-4fe838567bbb)

**Comment by Nerwyn** [comment]
My bad, I forgot to mark the build as pre-release. It shouldn't show up now.

Once I implement some of the style options I'll come back to this thread to talk about them if you want to try them out.

**Comment by Nerwyn** [comment]
Putting my notes here as I write the README another day but the latest dev build is pretty much a release candidate minus a couple of features which I may put off for a future build.

In version three, there are new style options for different elements which can take normal CSS properties or some custom ones as listed below

`button_style` for all buttons, or `style` within a custom key or source for a specific button
- `--size` - Sets button height and width
- `color` - Sets button color
- `background-image` - Sets button to an image
  - Use with `background-size: contain`, `background-repeat: no-repeat`, and `background-position: center`

`slider_style`
- `--color` - thumb/percentage on color
- `--background` - background color
- `--background-height` - background height
- `--border-radius` - slider border radius
- `height` - slider height, constrains `--background-height`

`touchpad_style`
- `height` - touchpad height
  - `touchpad_height` still works and internally gets copied to this new style object if it does not exist
- `background` - touchpad color
- `background-image` - image to overlay on touchpad
  - Use with `background-size: contain`, `background-repeat: no-repeat`, and `background-position: center`
- `opacity` - touchpad opacity

**Comment by Nerwyn** [comment]
Try this with version three:
```yaml
button_style:
  '--size': 24px
  background: rgb(27,27,27)
  padding: 8px
  border-radius: 5em
  color: rgb(187,187,187)
card_mod:
  style: |
    ha-card {
      background-color: rgba(27,27,27,0);
    }
```

**Comment by tikel1** [comment]
Wow thanks, looks extremely helpful. You rock!

**Comment by Nerwyn** [comment]
[v3.0.0 released](https://github.com/Nerwyn/android-tv-card/releases/tag/v3.0.0) with button, style, and touchpad style options.

**Comment by tikel1** [comment]
@Nerwyn Thanks! Looks good. I was able to convert all of the card-mod options and my remote looks great. 

![image](https://github.com/Nerwyn/android-tv-card/assets/121404448/c2392b5f-9070-4c36-b127-ebf84fb003d6)

**Comment by Nerwyn** [comment]
You could try setting the color to a CSS variable using card mod and then reference that in style. That's what [I recommended and worked for my other project](https://community.home-assistant.io/t/service-call-tile-features-sliders-and-buttons/620724/19?u=nerwyn).

```yaml
custom)_keys:
  volume_mute:
    key: mute
    style:
      color: var(--mute-color)
card_mod:
  style: |
    :host {
      --mute-color: {{ red if state_attr('media_player.sony_xr_65a80k', 'is_volume_muted') else white }}
    }
```
