### ISSUE TITLE
Vertical Sliders

### ISSUE THREAD

**Issue by Nerwyn** [Nerwyn/android-tv-card#25]
**Is your feature request related to a problem? Please describe.**
- ~~Need to copy over code for slider thumb options from service-call-tile-feature since styling it yourself is a massive pain.~~
- Need to figure out a way to gracefully support vertical sliders.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SteeledKnight** [comment]
Is there a way to make the slider vertical or is this planned to be implemented?

**Comment by Nerwyn** [comment]
Not yet. I'm hoping to make it possible using CSS `transform: rotate(270deg)` but the shadow roots Lit elements create make it tricky.

**Comment by Nerwyn** [comment]
In #63 I made it so that all rows and columns now have unique IDs for card-mod styling. By encapsulating the slider in it's own column and using a mix of card-mod and internal style options I was able to make a vertical slider! But if you try to do more than a small change using the slider swipe detection gets triggered. I'll have to add code to disable it if the slider is transformed.

```yaml
custom_actions:
  slider:
    style:
      transform: rotate(270deg);
      min-width: var(--slider-height);
card_mod:
  style:
    .: |
      #column-1 {
        min-width: 50px;
        min-height: var(--slider-height);

        --slider-height: 150px;
      }
      remote-slider {
        min-height: var(--slider-height);
      }
```

**Comment by Nerwyn** [comment]
In version 3.8.0 (currently in development), vertical sliders can be toggled using a new `vertical` field in slider custom actions. I wasn't able to get the slider height to auto extended to the height of it's parent flexbox but it can be set explicitly using `width`. No more card-mod styling needed either!

```yaml
custom_actions:
  slider:
    vertical: true
    style:
      width: 200px
```
