### ISSUE TITLE
RakutenTV

### ISSUE THREAD

**Issue by omakoti** [Nerwyn/android-tv-card#29]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hi. 
Update for skyshowtime was fast. Thanks for that.
I was hoping to get the RakutenTV too.
The Rakuten Viki that was added is not the one I was looking for. Hopefully the other Rakuten will be added later. Thanks for a great job.  👏

**Comment by Nerwyn** [comment]
Ah whoops. I was going by the Rakuten listed in the [deep linking guide list](https://community.home-assistant.io/t/android-tv-remote-app-links-deep-linking-guide/567921).

In order to add Rakuten TV to the default sources list, I'll need to know it's activity. Following the guide linked above I found a few candidates:
- tv.wuaki.apptv
- rakutentv
- rakuten.tv
Can you create a custom source for each of these options as shown in the README and tell me which one works?

Like this:

```yaml
custom_sources:
  option_a:
    source: tv.wuaki.apptv
    icon: mdi:alpha-a
  option_b:
    source: rakutentv
    icon: mdi:alpha-b
  option_c:
    source: rakuten.tv
    icon: mdi:alpha-c
```

**Comment by omakoti** [comment]
Hi again.
I'm so bad at this. 🤦
Can't get the custom source option to work.
Probably just writing it to the wrong place. 
Where should I write the code for the custom source?
I was writing it to the  card confoguration when adding it. 🫣

**Comment by Nerwyn** [comment]
Like in [this example](https://github.com/Nerwyn/android-tv-card#example-10).

Your remote config should look something like this:

```yaml
remote_id: remote.google_chromecast
rows:
  - - option_a
    - option_b
    - option_c
custom_sources:
  option_a:
    source: tv.wuaki.apptv://
    icon: mdi:alpha-a
  option_b:
    source: rakutentv://
    icon: mdi:alpha-b
  option_c:
    source: rakuten.tv://
    icon: mdi:alpha-c
```
