### ISSUE TITLE
Template Support for Custom Keys

### ISSUE THREAD

**Issue by Ayuus** [Nerwyn/android-tv-card#34]
Hello,

I expected that custom buttons would allow me to write a template, so I tried to implement a toggle button for muted audio:

```
custom_keys:
  my_volume_mute:
    icon: mdi:volume-high
    service: media_player.volume_mute
    target:
      entity_id: media_player.lg_tv
    data:
      is_volume_muted: "{{ not state_attr('media_player.lg_tv', 'is_volume_muted') }}"

```
However, HA c omplains about "invalid value for Boolean". In Developer Tools, Templates, the code works OK.
