### ISSUE TITLE
Use android debug bridge screen capture for background

### ISSUE THREAD

**Issue by domeassist** [Nerwyn/android-tv-card#38]
I am trying to set the android debug bridge screenshot displayed on the android debug bridge entity card as a background for the remote. Or even the touchpad. 

I have tried various methods but cannot locate the file location android adb saves to and it doesn't display as an attribute of the android adb entity to reference.

Failing this being a feature, anyone got any ideas?

**Comment by Nerwyn** [comment]
I've added template support in [v3.1.0](https://github.com/Nerwyn/android-tv-card/releases/tag/v3.1.0). This works for me!!

```yaml
type: custom:android-tv-card
rows:
 - - touchpad
touchpad_style:
  background: url({{ state_attr("media_player.lounge_google_tv_adb", "entity_picture") }}
  background-size: contain
  background-repeat: no-repeat
  background-position: center
```
