### ISSUE TITLE
Sending Text Commands

### ISSUE THREAD

**Issue by Nerwyn** [Nerwyn/android-tv-card#4]
**Is your feature request related to a problem? Please describe.**
The ability to send text rather than using the TV keyboard would make using this remote even better than the physical one. It should be possible to use the existing Home Assistant integrations to send keystrokes to Android TVs.

**Describe the solution you'd like**
The ability to send keystrokes to Android TV.

**Describe alternatives you've considered**
The Google TV app has the best implementation of this, as it seems to live capture the contents of the text box you're interacting with and modify it in real time. I'm not sure how they are doing that or if it's part of Android TV Remote Protocol V2.

**Additional context**
Using the alphabetical keycodes listed [here](https://github.com/tronikos/androidtvremote2/blob/main/src/androidtvremote2/remotemessage.proto#L165) with `remote.send_command` frustratingly does nothing. I'm not sure if this is a bug in the integration, the underlying library, or Android TV Remote Protocol V2.

It is possible to send text to Android TVs using Home Assistant via ADB, but it isn't nearly as graceful as doing so from the Google TV app. I created an `input_text` entity and a script that when called, would send the contents of the textbox to the Android TV.
```yaml
alias: Lounge TV - Google TV Send Text
sequence:
  - service: androidtv.adb_command
    data:
      command: input text "{{ states("input_text.lounge_tv_google_tv_text_input") }}"
    target:
      entity_id: media_player.lounge_google_tv_adb
mode: single
icon: mdi:form-textbox
```
And a lovelace config to go with it that includes backspace functionality:
```yaml
type: entities
entities:
  - entity: input_text.lounge_tv_google_tv_text_input
    hold_action:
      action: call-service
      service: script.lounge_tv_google_tv_send_text
    tap_action:
      action: call-service
      service: remote.send_command
      data:
        entity_id: remote.lounge_google_tv
        command: KEYCODE_DEL
```
This method works but feels hacky and inelegant. I want to try to find a better solution, like one that would transmit keycodes to the Android TV live rather than in bulk.
