### ISSUE TITLE
add dpad_style

### ISSUE THREAD

**Issue by zampierilucas** [Nerwyn/android-tv-card#41]
**Is your feature request related to a problem? Please describe.**
I would love to customize the dpad to more closely match the google_tv app controller, also it would be nice to have an option to make the clickable boxes bigger.

**Comment by Nerwyn** [comment]
This one right?
![image](https://github.com/Nerwyn/android-tv-card/assets/43071698/fc2718ad-aa37-4788-b363-b29cf1bfb201)
This would definitely be nice to have, but it'll have to go in the backlog after the touchpad improvements I've been holding off on. I'll have to learn how to recreate it using JS/HTML/CSS.

**Comment by zampierilucas** [comment]
@Nerwyn yep that one, thank you for considering it :D

**Comment by Nerwyn** [comment]
@zampierilucas to clarify, did you want a new dpad that stylistically matched the Google TV one, or to be able to style the existing dpad? I was able to match the Google TV remote dpad using the existing style options.

```yaml
type: custom:android-tv-card
rows:
  - - dpad
custom_actions:
  center:
    style:
      color: rgb(95, 98, 104)
      '--size': 200px
      background-color: rgb(60, 64, 67)
      xborder-style: solid
      border-color: rgb(60, 64, 67)
      border-radius: 500px
      padding: 75px
  up:
    style:
      color: rgb(95, 98, 104)
      z-index: 2
      top: 100px
      height: 90px
      width: 170px
  down:
    style:
      color: rgb(95, 98, 104)
      z-index: 2
      bottom: 100px
      height: 90px
      width: 170px
  left:
    style:
      color: rgb(95, 98, 104)
      z-index: 2
      left: 100px
      height: 170px
      width: 90px
  right:
    style:
      color: rgb(95, 98, 104)
      z-index: 2
      right: 100px
      height: 170px
      width: 90px
```
![image](https://github.com/Nerwyn/android-tv-card/assets/43071698/3a92c1fa-1d35-41de-b377-7669b51f6ef5)

It does have some caveats, like the direction buttons being shifted from their original positions and resized such that their rows are empty and create large gaps.
