### ISSUE TITLE
AppleTV keyboard

### ISSUE THREAD

**Issue by jdemarc2** [Nerwyn/android-tv-card#45]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Can you add a keyboard for appleTV

**Describe alternatives you've considered**
Using the appletv remote on my iphone which supports keyboard use

**Additional context**

**Comment by Nerwyn** [comment]
In order to add Apple TV support the [Home Assistant Apple TV integration](https://www.home-assistant.io/integrations/apple_tv/) has to support sending text. Currently it does not, but [the underlying package](https://pyatv.dev/development/keyboard/) it uses does. Someone made [a feature request thread](https://community.home-assistant.io/t/appletv-integration-keyboard-commands/609229) about adding keyboard support to the Apple TV integration a few months ago but no one else responded.

Until keyboard support gets added to the Apple TV integration, adding Apple TV keyboard support to this card is not possible.

**Comment by houser42** [comment]
An obvious workaround if you are on iOS is to have a button to open  the Apple TV remote from within the HA app as that functionality is of course in there.
But probably just stating the bleeding obvious.

**Comment by Cha40s** [comment]
@houser42 would you mind to share your code with the button for Appetv Keyboard  integrated. would appreciate. I can remember I did similar with app:tvremote or something like that.

**Comment by houser42** [comment]
Of course @Cha40s . 
Below is the code for a button in my HA remote that opens the Apple TV remote on an iOS device:
Best wishes for 2024!

```
      - show_name: false
        show_icon: true
        type: button
        tap_action:
          action: url
          url_path: tvremote://
        icon: mdi:remote
        icon_height: 24px
```

... and here is also the code for a button that opens the Apple Music app if you need that too:

```
        
      - show_name: false
        show_icon: true
        type: button
        tap_action:
          action: url
          url_path: music://
        icon: mdi:music
        icon_height: 24px
```

**Comment by ngem1** [comment]
@Nerwyn this should now be possible with this [PR (keyboard commands)](https://github.com/home-assistant/core/pull/165638), which adds the following:

> Adds three new services to the Apple TV integration that expose pyatv's Keyboard interface for text input:
>
> - apple_tv.set_keyboard_text — Sets text in the currently focused text input field
> - apple_tv.append_keyboard_text — Appends text to the currently focused text input field
> - apple_tv.clear_keyboard_text — Clears the currently focused text input field

A real nice touch would be to also use this [PR (binary sensor)](https://github.com/home-assistant/core/pull/152397) to create notification when keyboard is active, like the Apple TV remote app does.

**Comment by Nerwyn** [comment]
The binary sensor usage is out of scope, but this will be the headline feature of the next minor version! I was going to do a patch version bump for a couple of other things but I'll roll them into this and work on it this week.

~This would also be a good opportunity to allow platforms that support both append and replace text to use both. I know it's a problem with Android TV being inconsistent about it.~

**Comment by ngem1** [comment]
Oh great! I look forward to trying it out!

**Comment by Nerwyn** [comment]
Can y'all try the 4.11 beta? I ended up only implementing set/replace text mode since it's superior to append mode when available.

**Comment by houser42** [comment]
> Can y'all try the 4.11 beta? I ended up only implementing set/replace text mode since it's superior to append mode when available.

I 'd be happy to try it. Any chance of some sample YAML to get started and show intended functionality?

If allowed, I would also like to sneak in a small related keyboard feature if it can be looked at?
There is one single command that I have been unable to get working, and that is not in the HA ATV integration.
Long-press the button in image below will take you to the settings and HomeKit options and it would be great to get this last key command working if it is possible via some magic from master @Nerwyn  ;)

<img width="322" height="370" alt="Image" src="https://github.com/user-attachments/assets/fe0a5257-a08c-46df-9d8a-f08c491996aa" />

**Comment by Nerwyn** [comment]
> I 'd be happy to try it. Any chance of some sample YAML to get started and show intended functionality?

Just create a remote with a `keyboard` and/or `textbox` key and platform Apple TV. Be sure to set your remote and config entry (new field required for Apple TV keyboard) IDs. Setting the config entry ID using the configuration UI should automatically fill in the remote and media player IDs.

```yaml
type: custom:universal-remote-card
platform: Apple TV
custom_actions: []
config_entry_id: f7eeb706538f43458922286bc357dfc0
remote_id: remote.apple_tv
media_player_id: media_player.apple_tv
rows:
  - - keyboard
    - textbox
```

> I would also like to sneak in a small related keyboard feature if it can be looked at?
There is one single command that I have been unable to get working, and that is not in the HA ATV integration.
Long-press the button in image below will take you to the settings and HomeKit options

No, that's not how this card works. The Apple TV integration has to support it, or you have to access it via another command like `url`. You may be able to access it using a deep link like you described above for the iOS Apple TV keyboard and Apple Music, but it's out of scope for this project.

**Comment by Nerwyn** [comment]
Anyone test it yet?

**Comment by Nerwyn** [comment]
Anyone else? @ngem1?

**Comment by ngem1** [comment]
Ive been trying to test but getting an issue with the Keyboard Focused binary sensor but being created. Ill keep trying to sort and update shortly

**Comment by Nerwyn** [comment]
The Apple TV keyboard focused binary sensory isn't needed for sending text to Apple TV and is more of a convenience feature of the integration not used by this card. You should just need the Apple TV config entry ID (and remote and media player IDs, but I made autofilling those based on the config entry ID a new feature for all platforms).

**Comment by Nerwyn** [comment]
If there's no feedback I'll release this later this week.

**Comment by Nerwyn** [comment]
It would be nice to release this knowing it works 😆 . And your feedback has always been helpful and appreciated houser.

**Comment by Nerwyn** [comment]
Apple TV does not have a way to open search directly so it does not have a search button on this remote. For any text field, it should be as simple as focusing on the field in Apple TV using the remote directional controls and then entering text using the card using either keyboard (seamless) or textbox (bulk) mode.

You can also try calling the Apple TV keyboard command with the [actions devtool](http://homeassistant.local:8123/config/developer-tools/action) to make sure it's working on your TV.

```yaml
action: apple_tv.set_keyboard_text
data:
  config_entry_id: your_apple_tv_config_entry_id
  text: text to send to tv
```

The config entry ID field is newly added for the Apple TV integration, but works with all platforms as a convenience feature to autofill the remote and media player entity IDs.
