### ISSUE TITLE
volume buttons doesn't work and image of button not showing

### ISSUE THREAD

**Issue by 1mfaasj** [Nerwyn/android-tv-card#56]
- Android tv card: 3.3.0-beta.009
- Home Assistant: the latest

Hi! is there something changed in the setup? Because I can't control the volume anymore, it doesn't react anymore when I click on one of the volume buttons.
Also the image of "nlziet" is not showing anymore. Weird because the image is still there when I open the URL and it worked before.
I've looked into the docs (frontend of your repo) and "card_mod" is not there. Is this recently changed? And maybe the reason it doesn't work?
![image](https://github.com/Nerwyn/android-tv-card/assets/71582854/d59fb4d3-539e-4652-9b84-26b566ad5d00)

My setup:
```
type: custom:android-tv-card
remote_id: remote.chromecastwoonkamer
media_player_id: media_player.samsung_au7100_70_tv
keyboard_id: media_player.android_tv_192_168_2_32
title: Chromecast
rows:
  - - back
    - power
    - home
    - search
  - - volume_down
    - volume_mute
    - volume_up
  - - navigation_buttons
  - - netflix
    - youtube
    - disney
    - spotify
    - videoland
    - nlziet
  - - previous
    - rewind
    - play_pause
    - fast_forward
    - next
custom_sources:
  videoland:
    source: videoland-v2://
  nlziet:
    source: nlziet://
card_mod:
  style: |
    ha-icon-button[title="videoland"] {
      background-image: url(https://cdn6.aptoide.com/imgs/3/c/8/3c8d26f1af6306c09b9cfa24fe679949_icon.png);
      background-repeat: no-repeat;
      background-size: contain;
    }
    ha-icon-button[title="nlziet"] {
      background-image: url(https://seeklogo.com/images/N/nlziet-logo-6FB1C30F53-seeklogo.com.png);
      background-repeat: no-repeat;
      background-size: contain;
    }
custom_keys:
  volume_down:
    service: media_player.volume_down
    service_data:
      entity_id: media_player.samsung_au7100_70_tv
  volume_mute:
    service: media_player.volume_mute
    service_data:
      entity_id: media_player.samsung_au7100_70_tv
      is_volume_muted: true
  volume_up:
    service: media_player.volume_up
    service_data:
      entity_id: media_player.samsung_au7100_70_tv
```

**Comment by Nerwyn** [comment]
What version were you on before this? card mod broke a while ago. You have to either account for the shadow roots within card mod or use the built in style options. You must be upgrading from a much older version.

While your config should continue to work otherwise, here it is upgraded to the latest version's syntax:

```yaml
type: custom:android-tv-card
remote_id: remote.chromecastwoonkame
slider_id: media_player.samsung_au7100_70_tv
keyboard_id: media_player.android_tv_192_168_2_32
title: Chromecast
rows:
  - - back
    - power
    - home
    - search
  - - volume_down
    - volume_mute
    - volume_up
  - - navigation_buttons
  - - netflix
    - youtube
    - disney
    - spotify
    - videoland
    - nlziet
  - - previous
    - rewind
    - play_pause
    - fast_forward
    - next
custom_actions:
  nlziet:
    tap_action:
      action: source
      source: nlziet://
    style:
      background-image: url(https://seeklogo.com/images/N/nlziet-logo-6FB1C30F53-seeklogo.com.png);
      background-repeat: no-repeat;
      background-size: contain;
      background-position-y: center;
custom_actions:
  volume_down:
    tap_action:
      action: call-service
      service: media_player.volume_down
      data:
        entity_id: media_player.samsung_au7100_70_tv
  volume_mute:
    tap_action:
      action: call-service
      service: media_player.volume_mute
      data:
        entity_id: media_player.samsung_au7100_70_tv
        is_volume_muted: true
  volume_up:
    tap_action:
      action: call-service
      service: media_player.volume_up
      data:
        entity_id: media_player.samsung_au7100_70_tv
```
