### ISSUE TITLE
programmable button_press & button_release

### ISSUE THREAD

**Issue by armedad** [Nerwyn/android-tv-card#58]
i'm trying to simulate how fastforward works on some services which is that tapping on fast forward jumps forward 10 secs.  but press and hold for a couple seconds activate fastforward.

what i've done to work around it is this:
```

  fast_forward:
    icon: mdi:fast-forward
    tap_action:
      service: androidtv.adb_command
      service_data:
        entity_id: media_player.main_bedroom_fire_tv
        command: >-
          sendevent /dev/input/event4 4 4 786611 && sendevent /dev/input/event4
          1 208 1 && sendevent /dev/input/event4 0 0 0 && sendevent
          /dev/input/event4 4 4 786611 && sendevent /dev/input/event4 1 208 0 &&
          sendevent /dev/input/event4 0 0 0    
    hold_action:
      service: script.androidtv_send_command_pair
      service_data:
        entity_id: media_player.main_bedroom_fire_tv
        command1: >-
          sendevent /dev/input/event4 4 4 786611 && sendevent /dev/input/event4
          1 208 1 &&  sendevent /dev/input/event4 0 0 0
        delay: 3
        command2: >-
          sendevent /dev/input/event4 4 4 786611 && sendevent /dev/input/event4
          1 208 0 && sendevent /dev/input/event4 0 0 0

```

what i'd like to do is this:
```

  fast_forward:
    icon: mdi:fast-forward
    tap_action:
      service: androidtv.adb_command
      service_data:
        entity_id: media_player.main_bedroom_fire_tv
        command: >-
          sendevent /dev/input/event4 4 4 786611 && sendevent /dev/input/event4
          1 208 1 && sendevent /dev/input/event4 0 0 0 && sendevent
          /dev/input/event4 4 4 786611 && sendevent /dev/input/event4 1 208 0 &&
          sendevent /dev/input/event4 0 0 0    
    button_press:
      service: androidtv.adb_command
      service_data:
        entity_id: media_player.main_bedroom_fire_tv
        command: >-
          sendevent /dev/input/event4 4 4 786611 && sendevent /dev/input/event4
          1 208 1 &&  sendevent /dev/input/event4 0 0 0
    button_release:
      service: androidtv.adb_command
      service_data:
        entity_id: media_player.main_bedroom_fire_tv
        command: >-
          sendevent /dev/input/event4 4 4 786611 && sendevent /dev/input/event4
          1 208 0 && sendevent /dev/input/event4 0 0 0


```

**Comment by Nerwyn** [comment]
So if I'm understanding this correctly, this would add a new action `hold_end_action`. `tap_action` would trigger normally, then if the button is held down long enough (500 ms) `hold_action` will trigger, and then on, and then finally when the button is released `hold_end_action` will trigger?

**Comment by armedad** [comment]
for me, my preference would not be hold_end, although that would probably
work.  i'd like to catch the initial press down.

the fire tv remote fires a sendevent right at the button press time, and a
release event on the button press release.   android then determines what
to do with it.  so my preference is to simulate exactly what the physical
remote is doing.

what you are suggesting on the hold_action would certainly work, as well,
however it would have 2 downsides.

imagine that prime video did the fast forward only when you held down the
button for 1000ms.  if the events fired on hold_action and on
hold_end_action, then the user would need to hold down for 1500ms in order
to achieve what the physical remote does in 1000ms.

that make sense?  sorry if my explanation is convoluted....

**Comment by Nerwyn** [comment]
That makes sense, it would just mean that you could not have hold start/end actions on the same button that has a tap action. We could also make it so that the `hold_secs` number that gets sent with the hold end action counts from the initial hold start event, so it counts up from 500 ms. That way you would still only need to hold for 1000 ms, but the initial hold start action wouldn't be sent until 500 ms.

I could possible implement both, and make it so that `hold_end_action` triggers if `hold_action` or `hold_start_action` is initially triggered (as described in my first comment), and then if `hold_start_action` is defined it disables `tap_action` and `hold_action`.

**Comment by armedad** [comment]
yeah...

in this particular case i'd have to choose..  not sure if you recall
programming keyboards and virtual keys in the windows world, but this is
like the high level sending vk_keys...  vk_return, vk_a, etc.  versus
sending scan codes...

if you're trying to automate entry into a text box, you'd do the vk_keys
(which is like sending an "a") .  but if you're trying to create a
virtual keyboard, you really want to do the raw scan codes because you then
actually simulate the keyboard and all the nuances.

**Comment by Nerwyn** [comment]
So `button_press` and `button_release` would replace the normal tap/double/hold actions if they're configured for a button?

**Comment by armedad** [comment]
generally yes.  I don't know if someone might find a reason to also use
those events, but in traditional keyboard implementations one would choose
one or the other.

**Comment by Nerwyn** [comment]
This should be working in [3.4.0-beta.001](https://github.com/Nerwyn/android-tv-card/releases/tag/3.4.0-beta.001). Can you try installing it and a command like this?

```yaml
custom_actions:
  fast_forward:
    icon: mdi:fast-forward
    momentary_start_action:
      action: call-service
      service: androidtv.adb_command
      data:
        entity_id: media_player.main_bedroom_fire_tv
        command: >-
          sendevent /dev/input/event4 4 4 786611 && sendevent /dev/input/event4
          1 208 1 &&  sendevent /dev/input/event4 0 0 0
    momentary_end_action:
      action: call-service
      service: androidtv.adb_command
      data:
        entity_id: media_player.main_bedroom_fire_tv
        command: >-
          sendevent /dev/input/event4 4 4 786611 && sendevent /dev/input/event4
          1 208 0 && sendevent /dev/input/event4 0 0 0
```
You can also include `HOLD_SECS` in the service call data value if possible for momentary end actions.
