### ISSUE TITLE
Row/Column Styling and Card-Mod Style Style Options

### ISSUE THREAD

**Issue by houser42** [Nerwyn/android-tv-card#63]
Just wondering if  this excellent card by any chance could be used to create a vertical stack with buttons in one column to the side?

The pic below is something I did in another defunct software many years ago. I would like to recreate the stack circled in green on the right if possible.
It is all volume controls with repeating buttons as can be done in this card. 
This should be next to the swipe gesture area already created with this card.
Any way to do this? Maybe the touchpad could at least have a vertical stack of small buttons on the side?

<img width="207" alt="Screenshot 2024-02-22 at 10 17 17" src="https://github.com/Nerwyn/android-tv-card/assets/15192440/60d3b487-1137-4499-a62e-385a97baab01">

**Comment by Nerwyn** [comment]
While overlay buttons on the touchpad isn't something I'm going to add separately, you can do it with `touchpad_style`

```yaml
type: custom:android-tv-card
rows:
  - - touchpad
    - 
    -
    -
    -
    -
    -
    - - volume_buttons
      - play_pause
      - home
      - fast_forward
      - previous
touchpad_style:
  position: absolute
  height: 500px
```

![image](https://github.com/Nerwyn/android-tv-card/assets/43071698/c797fdf0-3695-49fc-a3ec-dc9c8952152b)

**Comment by houser42** [comment]
Ok, thanks! Will try that!

**Comment by houser42** [comment]
Tried that and it kinda works but gets messy.  Will try some more..
Is it also possible to have a different  entity: media_player.xxx for the volume controls
as in this case the player is Kodi or Apple TV but the volume controls are for the AVR?

I'll just also leave a wish for the future: programmable overlay buttons on the touchpad that follows the theme.
Ah well. One can dream ;) Happy user here ;) Be safe, be well.

**Comment by Nerwyn** [comment]
For the slider, just changed `slider_id` to the other media player. For buttons, create custom actions for `volume_up`, `volume_down`, and `volume_mute` and call the correct services.

**Comment by Nerwyn** [comment]
Here's an updated config for making the touchpad the entire background:

```yaml
type: custom:android-tv-card
rows:
  - - touchpad
    - - null
      - null
      - null
      - null
      - null
      - null
      - home
      - null
      - null
      - null
      - null
      - back
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - null
    - - volume_buttons
      - play_pause
      - home
      - fast_forward
      - previous
touchpad_style:
  position: absolute
  height: 100vh
  width: 100vw
  top: 0px
  bottom: 0px
  left: 0px
  right: 0px
  border-radius: 0px
```

**Comment by Nerwyn** [comment]
Actionable improvements:
- [ ] Add IDs to all rows and columns so they can be individually styled using card_mod.
- [ ] See if it's possible to accept and apply an entire CSS style from the user instead of individual values, which can end up entirely replacing the old CSS system.

**Comment by Nerwyn** [comment]
@houser42 In the latest beta I've added IDs to rows and columns so they can be individually styled using card-mod. This should allow you to align columns to the left or right correctly.

```yaml
type: custom:android-tv-card
rows:
  - - touchpad
    - - back
    - - volume_buttons
      - play_pause
      - home
      - fast_forward
      - previous
touchpad_style:
  position: absolute
  height: 100%
  width: 100%
  top: 0px
  bottom: 0px
  left: 0px
  right: 0px
  border-radius: 0px
card_mod:
  style: |
    #column-1 {
      align-items: flex-start !important;
    }
    #column-2 {
      align-items: flex-end !important;
    }
```
![image](https://github.com/Nerwyn/android-tv-card/assets/43071698/85387590-771b-4a66-ad9d-ee0313eb0581)
![image](https://github.com/Nerwyn/android-tv-card/assets/43071698/da72af3d-e3bf-4995-a9fa-5206134166ac)

I also want to look into making it so that full CSS styles can be included in this card without card-mod so that they can be applied before render, but that will have to wait for another time.

**Comment by Nerwyn** [comment]
And here's the closest I could get to your old remote:

```yaml
type: custom:android-tv-card
rows:
  - - touchpad
    - - null
      - home
      - play_pause
    - - menu
    - - n7
      - n6
      - n5
      - n4
      - n3
      - volume_mute
      - volume_up
      - volume_down
touchpad_style:
  position: absolute
  height: 100%
  width: 100%
  top: 0px
  bottom: 0px
  left: 0px
  right: 0px
  border-radius: 0px
  background-image: >-
    url('https://hyken.com/wp-content/uploads/2023/01/Apple-TV-Logo-2019-present.png')
  background-size: 64px
  background-repeat: no-repeat
  background-position: center
  opacity: 1
card_mod:
  style: |
    #row-1 {
      align-items: stretch !important;
    }
    #column-1 {
      align-items: flex-start !important;
      justify-content: space-between !important;
    }
    #column-2 {
      justify-content: flex-end !important;
    }
    #column-3 {
      align-items: flex-end !important;
      justify-content: flex-end !important;
    }
```
![image](https://github.com/Nerwyn/android-tv-card/assets/43071698/fb13d330-f773-4f47-967e-494227813e3e)

I think this meets your original criteria, but I'm going to delay releasing it outside of alpha/beta or closing this card until I figure out if I can make it possible to apply the row/column styles without card-mod. If I can it may be worthy of a major release as it could change how styles are defined entirely.
