### ISSUE TITLE
Collapse when TV is off / minimized mode

### ISSUE THREAD

**Issue by ISilvaPT** [Nerwyn/android-tv-card#64]
Hi,

I think having the ability to collapse the remote when the TV is off (or at will) would be a nice feature to have, it would make the dashboards look more clean when the TV is not in use.

When collapsed the on/off button could still available, maybe more buttons too, like a configurable minimize mode and to have the ability to turn on the TV.

Thanks for all the hard work!

**Comment by Nerwyn** [comment]
This is already possible using templates:

```yaml
rows:
  - |
    {% if is_state("remote.google_tv", "on") %}
    - - back
      - home
      - menu
    - - keyboard
      - textbox
      - search
      - delete
      - enter
    - - vol_buttons
    - - slider
    - - dpad
      - touchpad
    - - rewind
      - play_pause
      - fast_forward
    {% endif %}
```

It does leave behind an empty button when off, which gives it the height of a normal row.

You can fully get rid of the card using card-mod

```yaml
card_mod:
  style: |
    ha-card {
      {% if is_state("remote.lounge_google_tv", "off") %}
        display: none;
      {% endif %}
    }
```

You could also limit the size of these empty rows or buttons by creating a custom action with `display: none` and putting that in the else statement of the template, or by using card-mod to set the style of empty buttons to `display: none`.

```yaml
rows:
  - |
    {% if is_state("remote.google_tv", "on") %}
...
    {% else %}
    empty-button
    {% endif %}
custom_actions:
  empty_button:
    style:
      display: none
```

```yaml
card_mod:
  style: |
    ha-card {
      {% if is_state("remote.lounge_google_tv", "off") %}
        display: none;
      {% endif %}
    }
    .empty-button {
      display: none;
    }
```
