### ISSUE TITLE
Multiple instances of the card in same view not working

### ISSUE THREAD

**Issue by LucaLa2001** [Nerwyn/android-tv-card#67]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
3.4.0

**Last working release (if known):**

**Browser and Operating System:**

Chrome on Windows 11, but the same issue occurs also on companion app on android

**Description of problem:**

When in the same view there are multiple instances of android-tv-card with different media players all volume's sliders of all card in the view control the volume of the entity defined in the last card.

**Javascript errors shown in the web inspector (if applicable):**
In web inspector shows no errors

**Your Full Remote Config**

```yaml

```

**Additional information:**
I have a tv and a speaker, so I'm using one instance of the card for the tv and another one for the speaker with only the volume slider. I noticed this issue with the volume, but maybe it occurs also with other commands, like the touchapd, unfortunately I can't verify this at the moment.

**Comment by LucaLa2001** [comment]
Sorry I forgot, here is the code of my view

```yaml
  - title: test
    path: test
    badges: []
    cards:
      - type: custom:android-tv-card
        remote_id: remote.tv_luca
        slider_id: media_player.tv_luca
        keyboard_id: media_player.tv_luca_adb
        rows:
          - - volume_mute
            - volume_down
            - volume_up
          - - touchpad
          - - back
            - play_pause
            - home
            - keyboard
      - type: custom:android-tv-card
        slider_id: media_player.luca
        rows:
          - - volume_slider
```
