### ISSUE TITLE
Buttons do not work on native Home Assistant app for macOS

### ISSUE THREAD

**Issue by JiDoan** [Nerwyn/android-tv-card#70]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
3.5.0

**Last working release (if known):**
Unsure

**Browser and Operating System:**
Native macOS app 2024.2, macOS 14.4

**Description of problem:**
The buttons on the remote no longer work on the native Home Assistant companion app that is downloaded from the App Store for macOS. The same remote works on any other browser or on iOS. The buttons used to work at some point in time but I do not know which version broke the remote. I think the companion app update broke it and not an update to android-tv-card, but I cannot confirm.

**Javascript errors shown in the web inspector (if applicable):**
Unable to open web inspector with companion app.

**Your Full Remote Config**

```yaml
type: custom:android-tv-card
remote_id: remote.living_room_tv
media_player_id: media_player.living_room_tv
keyboard_id: media_player.android_tv_sony
alt_volume_icons: true
rows:
  - - power
    - null
    - search
    - keyboard
  - - youtube
    - max
    - plex_alt
  - navigation_buttons
  - - back
    - home
    - tv
  - - volume_buttons
custom_sources:
  plex_alt:
    icon: phu:plex
    source: plex://

```

**Additional information:** 
N/A
