### ISSUE TITLE
Default entity_id for custom calls

### ISSUE THREAD

**Issue by kingy444** [Nerwyn/android-tv-card#73]
**Is your feature request related to a problem? Please describe.**

More of a code clean up (yaml) request and easy of changing devices. You have entity definitions for remote_id and slider_id. Could we have a new entity definition field that can be used as "default for custom calls"

**Describe the solution you'd like**
I am thinking at the top of the card we can define something like
``media_player_id: media_player.lounge_tv``

then rather then having to change all ``tap_action`` as below
```
tap_action:
      action: call-service
      service: media_player.play_media
      data:
        entity_id: media_player.lounge_tv
        media_content_type: send_key
        media_content_id: KEY_0
```
they could be defined as something like the below
```
tap_action:
      action: call-service
      service: media_player.play_media
      data:
        media_content_type: send_key
        media_content_id: KEY_0
```
Essentially then when you build the service call do something like
```
if entity_id:
  # use entity_id in service call
else
  # use media_player_id
```

**Comment by Nerwyn** [comment]
So s global value for `media_player_id` that autopopulates any media player service calls similar to how the `key` and `source` work with `remote_id`. I should probably also make it so that `remote_id` autopopulates service calls as well. In order to prevent undesirable behavior, I'm going to also add a flag `autofill_entity_id` which defaults to false which will enable this behavior for service calls.

**Comment by Nerwyn** [comment]
@kingy444 this remote config is working for me as of the latest 3.5.3 alpha (alpha.015). Can you give it a try?

```yaml
type: custom:android-tv-card
media_player_id: media_player.spotify
autofill_entity_id: true
rows:
  - - slider
    - previous
    - next
    - play_pause
custom_actions:
  previous:
    tap_action:
      action: call-service
      service: media_player.media_previous_track
  play_pause:
    tap_action:
      action: call-service
      service: media_player.media_play_pause
  next:
    tap_action:
      action: call-service
      service: media_player.media_next_track
  slider:
    style:
      '--tooltip-label': '{{ (100 * VALUE) | int }}%'
```
