### ISSUE TITLE
option to search by voice

### ISSUE THREAD

**Issue by ntk9** [Nerwyn/android-tv-card#75]
it will be great to have option to search by voice and not only keyboard, great remote! thank you!

**Comment by Nerwyn** [comment]
Home Assistant supports text to speech with easy to use service calls, but does not have an equivalent for speech to text. The closest thing it has is the `assist` action, which allows you to convert speech to Home Assistant commands through a dialogue. This action is currently supported.

```yaml
custom_actions:
  assist:
    icon: mdi:assistant
    tap_action:
      action: assist
```

As far as I can tell, there isn't a way to send speech to Home Assistant and get text back to use without using it as a command outside of the assist dialogue. If anyone else knows how to we can work on implementing this as a new text input method.
