### ISSUE TITLE
Add Stremio as a source

### ISSUE THREAD

**Issue by ROBOT0-VT** [Nerwyn/android-tv-card#90]
**Is your feature request related to a problem? Please describe.**
Add the [Strem.io](https://strem.io) app as a source

**Describe the solution you'd like**
Implementation of the source, in a similar way to Youtube, etc.

The documentation for deeplinking is [here](https://stremio.github.io/stremio-addon-sdk/deep-links.html), but the TLDR is that you can use `stremio://` as the source URL

**Describe alternatives you've considered**
Manual implementation:
```yaml
custom_actions:
  stremio:
    icon: mdi:play-circle
    tap_action:
      action: source
      source: stremio://
```
