### ISSUE TITLE
Example 15 no longer works 

### ISSUE THREAD

**Issue by chuppito** [Nerwyn/android-tv-card#93]
Hello, Example 15 worked well before, today it no longer works. I made home assistant updates today I guess the problem comes from there.

```
type: custom:android-tv-card
remote_id: remote.google_tv
rows:
  - - dpad
custom_actions:
  center:
    style:
      color: rgb(94, 94, 94)
      '--size': 200px
      background: rgb(31, 31, 31)
      border-radius: 200px
      margin: '-70px'
      padding: 70px
  up:
    style:
      color: rgb(197, 199, 197)
      z-index: 2
      top: 25px
      height: 90px
      width: 300px
  down:
    style:
      color: rgb(197, 199, 197)
      z-index: 2
      bottom: 25px
      height: 90px
      width: 300px
  left:
    style:
      color: rgb(197, 199, 197)
      z-index: 2
      left: 30px
      height: 170px
      width: 90px
  right:
    style:
      color: rgb(197, 199, 197)
      z-index: 2
      right: 30px
      height: 170px
      width: 90px
row_styles:
  row-1:
    justify-content: center
  row-2:
    justify-content: center
  row-3:
    justify-content: center
```
![Uploading Screenshot_20240613-190742.png…]()
