### ISSUE TITLE
Show current volume in volume slider as an alternative to icon

### ISSUE THREAD

**Issue by queimadus** [Nerwyn/android-tv-card#98]
**Is your feature request related to a problem? Please describe.**
We are only able to set an icon in the slider.

**Describe the solution you'd like**
It would be nice if instead of the icon, we could show the current volume. (Or allow showing the volume any other place in the widget)

Example:

| Before | After |
|-------|-------|
|      <img width="429" alt="Screenshot 2024-06-21 at 19 06 29" src="https://github.com/Nerwyn/android-tv-card/assets/1107697/087da381-5c52-4ae4-8df1-fc5e7f5f8bc2">      |       <img width="428" alt="Screenshot 2024-06-21 at 19 06 24" src="https://github.com/Nerwyn/android-tv-card/assets/1107697/590b478a-baf9-48d0-879e-8fdcd67fcae5">     |

**Comment by Nerwyn** [comment]
This is technically a duplicate of #78. I plan on porting over a lot of code from [one of my other projects](https://github.com/Nerwyn/service-call-tile-feature), which includes labels. Labels can then be used to display the current value of the slider and stylized to transform like the icon does. I won't get around to this until the next major version of that project is complete though.

**Comment by mk89pwnz** [comment]
Sorry for commenting on completed issue but was this merged or still I can't do this atm? as I can't find any example.

**Comment by Nerwyn** [comment]
You can add labels in version 4, which is a very in progress alpha. Labels can be set to display the slider element value.

The configuration UI in version 4 will modify your configs to the new format and it's still buggy and incomplete, so use at your own risk.

**Comment by queimadus** [comment]
An effect similar to the screenshot can now be achieved with something like:
```css
:host {
  --tooltip-label: '{{ (100 * VALUE) | int }}%';
  --label-transform: translateX(var(--thumb-offset));
}
.label {
  font-size: 20px;
  margin-bottom: 6px;
  background-color: #1c1c1c;
  color: #e1e1e1;
  width: 35px;
  padding: 10px 0;
  border-radius: 50%;
}
```
